/* eslint-disable */

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**
	 *  Start a live scan of `root` as a background job (F-104), returning
	 *  immediately with the new job's id.
	 * 
	 *  Records a `running` `jobs` row, registers a [`CancelFlag`] under the job id so
	 *  [`scan_cancel`] can stop it, spawns `abo_core::scan::run_scan_with_job` on
	 *  Tauri's async runtime with a progress sink that emits `job:progress`, and
	 *  returns [`JobStarted`] straight away so the IPC call never blocks on the walk.
	 *  When the spawned scan reaches a terminal state the task marks the `jobs` row:
	 *  `completed` (emits `job:completed { job_id, scan_id }`), `failed` with the
	 *  stable error `code` (emits `job:failed { job_id, code }`), or `cancelled` (no
	 *  event: the requester already knows, and the `jobs` row is the durable signal).
	 *  The cancel flag is deregistered once the job is terminal, whichever way it ends.
	 * 
	 *  `root` arrives as a plain string from the frontend because this release has no
	 *  dialog plugin; the backend-mediated folder picker (tauri-plugin-dialog, F-909)
	 *  arrives at v0.4.0 with the capability-model change it needs. That is acceptable
	 *  because the tracer UI is disposable (FD-29).
	 */
	scanStart: (root: string) => typedError<JobStarted, AppError>(__TAURI_INVOKE("scan_start", { root })),
	/**
	 *  Request cancellation of a running scan job (F-104, FD-02 cooperative Stop).
	 * 
	 *  Flips the [`CancelFlag`] registered for `job_id`, which the running scan
	 *  observes at its next safe entry boundary and stops there (discarding its
	 *  partial snapshot; see `run_scan_with_job`). Returns `true` if a running job
	 *  was found and signalled, `false` if no such in-flight job exists (already
	 *  finished, never started, or unknown id) - a clear no-op status, not an error
	 *  (a cancel of a not-running job is expected and harmless).
	 * 
	 *  Synchronous: it only flips an atomic in managed state, so it needs no async
	 *  runtime and returns instantly without waiting for the scan to actually stop.
	 */
	scanCancel: (jobId: number) => __TAURI_INVOKE<boolean>("scan_cancel", { jobId }),
	/**
	 *  Read every entry of a completed snapshot back for the tracer UI (F-105).
	 * 
	 *  Thin wrapper over [`abo_core::scan::get_scan_entries`]; returns the rows
	 *  path-sorted, exactly as the core produced them.
	 */
	scanEntries: (scanId: number) => typedError<EntryRow[], AppError>(__TAURI_INVOKE("scan_entries", { scanId })),
	/**
	 *  Report whether startup had to recover a corrupt database (P2).
	 * 
	 *  Reads the [`DbOpenOutcome`] captured at startup out of managed state and maps
	 *  it to the wire [`DbStatus`]. Synchronous: it only reads already-resolved
	 *  state, so it needs no async runtime.
	 */
	dbStatus: () => __TAURI_INVOKE<DbStatus>("db_status"),
};

/** Events */
export const events = {
	jobCompleted: makeEvent<JobCompleted>("job:completed"),
	jobFailed: makeEvent<JobFailed>("job:failed"),
	jobProgress: makeEvent<JobProgress>("job:progress"),
};

/* Types */
/**
 *  The Audiobook Organizer error taxonomy.
 * 
 *  Serialized across IPC as an externally-tagged enum whose tag is the stable
 *  kebab-case machine code (e.g. `db-migration-failed`). Deriving `serde` both
 *  ways and `specta::Type` makes `Result<T, AppError>` a valid tauri-specta
 *  command return type once the seam is wired (Phase 5).
 */
export type AppError = 
/**
 *  The database could not be created, opened, or migrated (and recovery to a
 *  fresh database also failed). This is the hard-failure end of the startup
 *  path; the recoverable case surfaces as [`DbCorruptRecovered`].
 * 
 *  [`DbCorruptRecovered`]: AppError::DbCorruptRecovered
 */
({ "db-migration-failed": {
	detail: string,
} }) & { "csv-parse"?: never; "db-corrupt-recovered"?: never; "junction-skipped"?: never; "permission-denied"?: never; "root-not-directory"?: never; "root-not-found"?: never; "ruleset-invalid"?: never; "scan-failed"?: never } | 
/**
 *  The existing database was unreadable and was reset. The corrupt file was
 *  preserved (moved aside, never deleted) at `backup_path`, and a fresh,
 *  migrated database is in use. Non-fatal: surfaced by the shell as a
 *  one-time family-safe notice, not a blocking error.
 */
({ "db-corrupt-recovered": {
	backup_path: string,
} }) & { "csv-parse"?: never; "db-migration-failed"?: never; "junction-skipped"?: never; "permission-denied"?: never; "root-not-directory"?: never; "root-not-found"?: never; "ruleset-invalid"?: never; "scan-failed"?: never } | 
/**  The scan root does not exist. Return before any DB row is written. */
({ "root-not-found": {
	path: string,
} }) & { "csv-parse"?: never; "db-corrupt-recovered"?: never; "db-migration-failed"?: never; "junction-skipped"?: never; "permission-denied"?: never; "root-not-directory"?: never; "ruleset-invalid"?: never; "scan-failed"?: never } | 
/**  The scan root exists but is not a directory (e.g. a file was chosen). */
({ "root-not-directory": {
	path: string,
} }) & { "csv-parse"?: never; "db-corrupt-recovered"?: never; "db-migration-failed"?: never; "junction-skipped"?: never; "permission-denied"?: never; "root-not-found"?: never; "ruleset-invalid"?: never; "scan-failed"?: never } | 
/**
 *  A single entry could not be read because the OS denied access. Defined
 *  and ready for v0.2.0: the v0.1.0 walk records such entries and counts
 *  them in [`ScanSummary::skipped_count`](crate::ipc::ScanSummary) rather
 *  than surfacing this per-entry error (AC-11), so a locked subtree never
 *  aborts a scan. Wiring the walk to emit this per entry is a v0.2.0
 *  concern; the code, message, and remediation are pinned here so the IPC
 *  contract is stable before then. Not produced by `run_scan` yet.
 */
({ "permission-denied": {
	path: string,
} }) & { "csv-parse"?: never; "db-corrupt-recovered"?: never; "db-migration-failed"?: never; "junction-skipped"?: never; "root-not-directory"?: never; "root-not-found"?: never; "ruleset-invalid"?: never; "scan-failed"?: never } | 
/**
 *  A junction or reparse point was recorded but deliberately not followed
 *  (D-09), so the walk cannot loop through a link back into the tree.
 *  Defined and ready for v0.2.0 on the same footing as
 *  [`PermissionDenied`](AppError::PermissionDenied): the v0.1.0 walk counts
 *  the skip on the summary rather than emitting this per-entry error, and
 *  wiring it per entry is a v0.2.0 concern. Not produced by `run_scan` yet.
 */
({ "junction-skipped": {
	path: string,
} }) & { "csv-parse"?: never; "db-corrupt-recovered"?: never; "db-migration-failed"?: never; "permission-denied"?: never; "root-not-directory"?: never; "root-not-found"?: never; "ruleset-invalid"?: never; "scan-failed"?: never } | 
/**
 *  An internal failure while writing the snapshot (a SQLite/transaction
 *  error during the scans/entries write path). The walk itself never fails
 *  this way; this is the DB-side hard-failure end of `run_scan`.
 */
({ "scan-failed": {
	detail: string,
} }) & { "csv-parse"?: never; "db-corrupt-recovered"?: never; "db-migration-failed"?: never; "junction-skipped"?: never; "permission-denied"?: never; "root-not-directory"?: never; "root-not-found"?: never; "ruleset-invalid"?: never } | 
/**
 *  A WizTree CSV import (F-102) could not fully parse. `row` is the 1-based
 *  index of the offending data row (the row after the header, preamble
 *  lines not counted), OR `0` reserved for a file-level/structural failure
 *  (the file could not be opened, or no WizTree header line was found at
 *  all) rather than a single bad data row.
 * 
 *  Isolated bad data rows (`row >= 1`) are recovered from: the row is
 *  skipped and the import continues with the rest of the file, so this
 *  variant surfaces as a per-row record the caller collects rather than as
 *  a hard `Err` in that case. A wholly invalid file (`row == 0`) IS a hard
 *  `Err` returned before any `scans` row is written, mirroring
 *  [`AppError::RootNotFound`]'s before-any-write posture.
 */
({ "csv-parse": {
	row: number,
} }) & { "db-corrupt-recovered"?: never; "db-migration-failed"?: never; "junction-skipped"?: never; "permission-denied"?: never; "root-not-directory"?: never; "root-not-found"?: never; "ruleset-invalid"?: never; "scan-failed"?: never } | 
/**
 *  A ruleset's JSON body could not be accepted: it is not valid JSON, is
 *  missing a required field, has a field of the wrong type, carries a
 *  `schema_version` this build does not support, or holds an out-of-range
 *  value (for example a series-index width below 1). Returned by
 *  [`crate::ruleset::parse_and_validate`] BEFORE any row is written, so a
 *  bad body is never persisted half-valid (AC-29). `detail` is a
 *  developer-facing explanation; the remediation is the user-facing one.
 */
({ "ruleset-invalid": {
	detail: string,
} }) & { "csv-parse"?: never; "db-corrupt-recovered"?: never; "db-migration-failed"?: never; "junction-skipped"?: never; "permission-denied"?: never; "root-not-directory"?: never; "root-not-found"?: never; "scan-failed"?: never };

/**
 *  Returned by the `db_status` command: the wire form of the startup
 *  [`crate::db::DbOpenOutcome`] (P2), reporting whether corrupt-DB recovery ran.
 * 
 *  [`crate::db::DbOpenOutcome`] is a startup-internal Rust type (it carries a
 *  `PathBuf`) and is deliberately NOT part of the IPC contract; the shell maps it
 *  to this serde/specta payload once, at the boundary. `recovered` is true
 *  exactly when the existing database was unreadable and was reset; when true,
 *  `backup_path` is where the prior database was preserved (the human-readable
 *  stored form), else `None`.
 */
export type DbStatus = {
	/**
	 *  True exactly when startup found a corrupt/unopenable database and reset it
	 *  (see [`crate::db::DbOpenOutcome::Recovered`]).
	 */
	recovered: boolean,
	/**  Where the corrupt database was preserved, when `recovered`; else `None`. */
	backup_path: string | null,
};

/**
 *  One persisted `entries` row (F-101 / F-105), read back for the tracer.
 * 
 *  The shape mirrors the `entries` table one-to-one. `parent_id` is the logical
 *  tree edge (the `entries.id` of the containing directory), `None` for the
 *  scan root. `kind` is `"file"` or `"dir"`; `file_class` is the F-103 class
 *  string for files and `None` for directories. `path` is the stored,
 *  human-readable full path (no `\\?\` prefix). `mtime` is ISO-8601 UTC, or
 *  `None` when the entry could not be stat'd.
 */
export type EntryRow = {
	/**  `entries.id` (assigned at insertion). */
	id: number,
	/**  The owning snapshot (`scans.id`). */
	scan_id: number,
	/**  Logical parent `entries.id`; `None` for the scan root. */
	parent_id: number | null,
	/**  Full path, stored form (no `\\?\` prefix). */
	path: string,
	/**  Final path component (file or directory name). */
	name: string,
	/**  `"file"` or `"dir"`. */
	kind: string,
	/**  F-103 file class for files (`audio`, `video`, ...); `None` for dirs. */
	file_class: string | null,
	/**  Size in bytes; 0 for directories and unstatable entries. */
	size: number,
	/**  Modification time (ISO-8601 UTC); `None` when unavailable. */
	mtime: string | null,
	/**  Depth below the scan root (root is 0). */
	depth: number,
};

/**  Typed `job:completed` event, emitted when a spawned scan finishes cleanly. */
export type JobCompleted = JobCompletedPayload;

/**
 *  Payload of the `job:completed` event, emitted when a spawned scan finishes
 *  successfully. Carries the originating `job_id` and the `scan_id` of the
 *  snapshot written, so the tracer can read the entries back.
 */
export type JobCompletedPayload = {
	/**  The `jobs.id` returned earlier by `scan_start`. */
	job_id: number,
	/**  The `scans.id` of the snapshot the completed scan wrote. */
	scan_id: number,
};

/**  Typed `job:failed` event, emitted when a spawned scan errors. */
export type JobFailed = JobFailedPayload;

/**
 *  Payload of the `job:failed` event, emitted when a spawned scan errors. Carries
 *  the originating `job_id` and the stable machine `code` from
 *  [`AppError::code`], so the frontend can key off the same codes the command
 *  results use.
 */
export type JobFailedPayload = {
	/**  The `jobs.id` returned earlier by `scan_start`. */
	job_id: number,
	/**  The stable kebab-case error code (equals [`AppError::code`]). */
	code: string,
};

/**
 *  Typed `job:progress` event.
 * 
 *  DEFINED but NEVER EMITTED in the v0.1.0 spine (this phase's brief): the spine
 *  scan is one spawned unit with no progress reporting or cancellation. It is
 *  collected into the `tauri_specta::Builder` alongside the other two so the
 *  generated bindings surface freezes the whole job-event contract now; a later
 *  release adds the emitter as an additive change. There is deliberately no
 *  `emit_*` helper for it here, precisely because nothing emits it yet.
 */
export type JobProgress = JobProgressPayload;

/**
 *  Payload of the `job:progress` event.
 * 
 *  Frozen NOW so the IPC contract is complete, even though the v0.1.0 spine
 *  NEVER emits it: the spine scan is a single spawned unit with no progress
 *  reporting or cancellation (this phase's brief). Wiring an emitter is a later
 *  release's concern; pinning the shape here means adding progress later is an
 *  additive change that does not perturb the frozen bindings surface.
 */
export type JobProgressPayload = {
	/**  The `jobs.id` this progress update belongs to. */
	job_id: number,
	/**  Units of work completed so far. */
	done: number,
	/**
	 *  Best-known total units, or `None` when the total is not yet known
	 *  (an indeterminate phase).
	 */
	total_estimate: number | null,
	/**
	 *  A short human-readable label for the current step (for example a path or
	 *  stage name).
	 */
	current_label: string,
};

/**
 *  Returned by the `scan_start` command the instant a scan is accepted (F-104).
 * 
 *  `scan_start` inserts a `running` `jobs` row, spawns the scan on the async
 *  runtime, and returns this immediately; the caller then waits for the
 *  [`JobCompletedPayload`] / [`JobFailedPayload`] event carrying the same
 *  `job_id`. This decouples the long-running scan from the IPC call.
 */
export type JobStarted = {
	/**
	 *  `jobs.id` of the row created for this scan; correlates the later
	 *  `job:completed` / `job:failed` event back to this call.
	 */
	job_id: number,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

