/* eslint-disable */

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**
	 *  Start a live scan of `root` as a background job (F-104), returning
	 *  immediately with the new job's id.
	 * 
	 *  Records a `running` `jobs` row, registers a [`CancelFlag`] under the job id so
	 *  [`scan_cancel`] can stop it, spawns `abo_core::scan::run_scan_with_job` on
	 *  Tauri's async runtime with a progress sink that emits `job:progress`, and
	 *  returns [`JobStarted`] straight away so the IPC call never blocks on the walk.
	 *  When the spawned scan reaches a terminal state the task marks the `jobs` row:
	 *  `completed` (emits `job:completed { job_id, scan_id }`), `failed` with the
	 *  stable error `code` (emits `job:failed { job_id, code }`), or `cancelled` (no
	 *  event: the requester already knows, and the `jobs` row is the durable signal).
	 *  The cancel flag is deregistered once the job is terminal, whichever way it ends.
	 * 
	 *  The scan root is NO LONGER a frontend argument (FD-29 re-allowance, v0.4.0
	 *  Phase 2): `scan_start` uses the backend's sanctioned library root, loaded from
	 *  persisted settings at startup and updated by `settings_set` when the user
	 *  picks or changes the library folder. The frontend cannot ask the backend to
	 *  scan an arbitrary path; the only way a path enters the backend is the OS folder
	 *  picker (`tauri-plugin-dialog`) -> `settings_set` -> persisted `library_root`.
	 *  If no library is configured (first-run not completed), there is nothing to
	 *  scan and this returns [`AppError::RootNotFound`] so the shell can route to
	 *  first-run / re-pick.
	 */
	scanStart: () => typedError<JobStarted, AppError>(__TAURI_INVOKE("scan_start")),
	/**
	 *  Request cancellation of a running scan job (F-104, FD-02 cooperative Stop).
	 * 
	 *  Flips the [`CancelFlag`] registered for `job_id`, which the running scan
	 *  observes at its next safe entry boundary and stops there (discarding its
	 *  partial snapshot; see `run_scan_with_job`). Returns `true` if a running job
	 *  was found and signalled, `false` if no such in-flight job exists (already
	 *  finished, never started, or unknown id) - a clear no-op status, not an error
	 *  (a cancel of a not-running job is expected and harmless).
	 * 
	 *  Synchronous: it only flips an atomic in managed state, so it needs no async
	 *  runtime and returns instantly without waiting for the scan to actually stop.
	 */
	scanCancel: (jobId: number) => __TAURI_INVOKE<boolean>("scan_cancel", { jobId }),
	/**
	 *  Read every entry of a completed snapshot back for the tracer UI (F-105).
	 * 
	 *  Thin wrapper over [`abo_core::scan::get_scan_entries`]; returns the rows
	 *  path-sorted, exactly as the core produced them.
	 */
	scanEntries: (scanId: number) => typedError<EntryRow[], AppError>(__TAURI_INVOKE("scan_entries", { scanId })),
	/**
	 *  Read one book's cover art for a snapshot entry (F-907, v0.4.0 Phase 3).
	 * 
	 *  `scan_id` + `entry_id` name a book WITHIN a snapshot (a book folder or a loose
	 *  audio file); the source paths are resolved from the snapshot's own `entries`
	 *  rows, so the frontend never supplies a filesystem path and the WebView can
	 *  never point cover reading at an unsanctioned location (FD-29). The engine reads
	 *  the cover STRICTLY read-only (embedded art or a `cover.jpg`/`folder.jpg`
	 *  sidecar) and caches the thumbnail under `app_data/covers` - outside the
	 *  library, so caching never touches the user's files (D-09, AC-21).
	 * 
	 *  Returns the [`CoverImage`] (mime + base64) so the WebView receives image data
	 *  over typed IPC, never a filesystem or asset-protocol scope. `None` means the
	 *  book has no cover, and the frontend renders the deterministic fallback tile
	 *  (AC-23). Only a genuine database read failure surfaces as an error; an
	 *  unreadable frame or absent sidecar degrades that one tile to the fallback
	 *  rather than breaking the shelf.
	 */
	coverGet: (scanId: number, entryId: number) => typedError<{
	/**  The image mime type, sniffed from the bytes (e.g. `image/jpeg`). */
	mime: string,
	/**  Standard base64 (RFC 4648, `=`-padded) of the raw image bytes. */
	base64: string,
} | null, AppError>(__TAURI_INVOKE("cover_get", { scanId, entryId })),
	/**
	 *  Read the library home's data (F-902, v0.4.0 Phase 4): the health facts, the
	 *  "Worth a look first" examples, the series clusters, and the good-news line,
	 *  all computed from the most recently COMPLETED scan.
	 * 
	 *  Returns `None` when no scan has ever completed - the honest pre-first-scan
	 *  state (AC-6): the frontend shows the empty-library state and the scan
	 *  affordance rather than treating an absent scan as a library of zero books.
	 *  The frontend never names a `scan_id` itself; this command is how it finds
	 *  "the library, right now."
	 * 
	 *  Classifying is cheap pure logic (no I/O beyond the one snapshot read), so
	 *  this command re-derives the classification and health metrics on every
	 *  call rather than caching them - the same freshness guarantee AC-7 asks for
	 *  (every count read at render time, never a stale cached one).
	 */
	classifyOverview: () => typedError<{
	/**
	 *  The snapshot this overview was computed from (`scans.id`); the frontend
	 *  passes this alongside a [`BookExample::entry_id`] to `cover_get`.
	 */
	scan_id: number,
	/**
	 *  Every book the library holds: one per `book`-class folder (a disc-split
	 *  book still counts once) plus one per loose-root audio file plus the
	 *  distinct titles F-203 found inside each `multi-book-suspect` folder.
	 */
	total_books: number,
	/**
	 *  Sum of file sizes across the whole snapshot (equals
	 *  [`HealthMetrics::total_bytes`]).
	 */
	total_bytes: number,
	/**
	 *  How many of `total_books` carry at least one "worth a look" problem
	 *  (loose file, messy folder name, a multi-book/box-set folder, or a
	 *  duplicate copy). `total_books - needs_tidy_books` is already tidy.
	 */
	needs_tidy_books: number,
	/**
	 *  A bounded set of example books for the "Worth a look first" shelf
	 *  (design-system Section 4.6-4.7): curated examples, not the exhaustive
	 *  list - the full list is the Phase 5 review surface and the exported
	 *  report (D-16).
	 */
	worth_a_look: BookExample[],
	/**  Real series containers on the shelves (design-system Section 4.8). */
	series: SeriesCluster[],
	good_news: GoodNews,
	/**
	 *  The full per-class/per-problem health report this overview was built
	 *  from, so the sidebar's Duplicates badge (FD-08 GROUP count) and any
	 *  other per-group count reads the same numbers the home prose does.
	 */
	metrics: HealthMetrics,
} | null, AppError>(__TAURI_INVOKE("classify_overview")),
	/**
	 *  Report whether startup had to recover a corrupt database (P2).
	 * 
	 *  Reads the [`DbOpenOutcome`] captured at startup out of managed state and maps
	 *  it to the wire [`DbStatus`]. Synchronous: it only reads already-resolved
	 *  state, so it needs no async runtime.
	 */
	dbStatus: () => __TAURI_INVOKE<DbStatus>("db_status"),
	/**
	 *  Read the singleton application settings (F-803, AC-34).
	 * 
	 *  Thin wrapper over [`abo_core::db::settings::get_settings`]. The frontend calls
	 *  this at startup to route first-run (a `None` `library_root` means no library
	 *  is configured) and to seed the theme from persisted settings (FD-09).
	 */
	settingsGet: () => typedError<AppSettings, AppError>(__TAURI_INVOKE("settings_get")),
	/**
	 *  Persist the singleton application settings (F-803, AC-34) and return the
	 *  stored result.
	 * 
	 *  After writing, this updates the backend's sanctioned scan root
	 *  ([`AppState::library_root`](crate::AppState::library_root)) to match the newly
	 *  persisted `library_root`, so a scan started after the user re-selects the
	 *  library folder operates on the new root immediately (FD-29 re-allowance). The
	 *  returned [`AppSettings`] is the normalized, persisted form (empty roots become
	 *  `None`, the theme is clamped to `day`/`evening`), so the caller sees exactly
	 *  what was stored.
	 */
	settingsSet: (settings: AppSettings) => typedError<AppSettings, AppError>(__TAURI_INVOKE("settings_set", { settings })),
};

/** Events */
export const events = {
	jobCompleted: makeEvent<JobCompleted>("job:completed"),
	jobFailed: makeEvent<JobFailed>("job:failed"),
	jobProgress: makeEvent<JobProgress>("job:progress"),
};

/* Types */
/**
 *  The Audiobook Organizer error taxonomy.
 * 
 *  Serialized across IPC as an externally-tagged enum whose tag is the stable
 *  kebab-case machine code (e.g. `db-migration-failed`). Deriving `serde` both
 *  ways and `specta::Type` makes `Result<T, AppError>` a valid tauri-specta
 *  command return type once the seam is wired (Phase 5).
 */
export type AppError = 
/**
 *  The database could not be created, opened, or migrated (and recovery to a
 *  fresh database also failed). This is the hard-failure end of the startup
 *  path; the recoverable case surfaces as [`DbCorruptRecovered`].
 * 
 *  [`DbCorruptRecovered`]: AppError::DbCorruptRecovered
 */
({ "db-migration-failed": {
	detail: string,
} }) & { "collision-in-plan"?: never; "collision-on-disk"?: never; "cross-volume-space-insufficient"?: never; "csv-parse"?: never; "cycle-detected"?: never; "db-corrupt-recovered"?: never; "illegal-component"?: never; "junction-skipped"?: never; "path-too-long"?: never; "permission-denied"?: never; "reserved-name"?: never; "root-not-directory"?: never; "root-not-found"?: never; "ruleset-invalid"?: never; "scan-failed"?: never; "settings-failed"?: never; "snapshot-stale"?: never } | 
/**
 *  The existing database was unreadable and was reset. The corrupt file was
 *  preserved (moved aside, never deleted) at `backup_path`, and a fresh,
 *  migrated database is in use. Non-fatal: surfaced by the shell as a
 *  one-time family-safe notice, not a blocking error.
 */
({ "db-corrupt-recovered": {
	backup_path: string,
} }) & { "collision-in-plan"?: never; "collision-on-disk"?: never; "cross-volume-space-insufficient"?: never; "csv-parse"?: never; "cycle-detected"?: never; "db-migration-failed"?: never; "illegal-component"?: never; "junction-skipped"?: never; "path-too-long"?: never; "permission-denied"?: never; "reserved-name"?: never; "root-not-directory"?: never; "root-not-found"?: never; "ruleset-invalid"?: never; "scan-failed"?: never; "settings-failed"?: never; "snapshot-stale"?: never } | 
/**
 *  The singleton application settings row (F-803) could not be read or
 *  written. A rare SQLite error on the settings CRUD path (`settings_get` /
 *  `settings_set`); `detail` is the developer-facing cause. Distinct from
 *  [`DbMigrationFailed`](AppError::DbMigrationFailed), which is the
 *  startup-time open/migrate failure, and from
 *  [`DbCorruptRecovered`](AppError::DbCorruptRecovered), the recovered
 *  startup case: this is a runtime read/write failure against an
 *  already-open, already-migrated database.
 */
({ "settings-failed": {
	detail: string,
} }) & { "collision-in-plan"?: never; "collision-on-disk"?: never; "cross-volume-space-insufficient"?: never; "csv-parse"?: never; "cycle-detected"?: never; "db-corrupt-recovered"?: never; "db-migration-failed"?: never; "illegal-component"?: never; "junction-skipped"?: never; "path-too-long"?: never; "permission-denied"?: never; "reserved-name"?: never; "root-not-directory"?: never; "root-not-found"?: never; "ruleset-invalid"?: never; "scan-failed"?: never; "snapshot-stale"?: never } | 
/**  The scan root does not exist. Return before any DB row is written. */
({ "root-not-found": {
	path: string,
} }) & { "collision-in-plan"?: never; "collision-on-disk"?: never; "cross-volume-space-insufficient"?: never; "csv-parse"?: never; "cycle-detected"?: never; "db-corrupt-recovered"?: never; "db-migration-failed"?: never; "illegal-component"?: never; "junction-skipped"?: never; "path-too-long"?: never; "permission-denied"?: never; "reserved-name"?: never; "root-not-directory"?: never; "ruleset-invalid"?: never; "scan-failed"?: never; "settings-failed"?: never; "snapshot-stale"?: never } | 
/**  The scan root exists but is not a directory (e.g. a file was chosen). */
({ "root-not-directory": {
	path: string,
} }) & { "collision-in-plan"?: never; "collision-on-disk"?: never; "cross-volume-space-insufficient"?: never; "csv-parse"?: never; "cycle-detected"?: never; "db-corrupt-recovered"?: never; "db-migration-failed"?: never; "illegal-component"?: never; "junction-skipped"?: never; "path-too-long"?: never; "permission-denied"?: never; "reserved-name"?: never; "root-not-found"?: never; "ruleset-invalid"?: never; "scan-failed"?: never; "settings-failed"?: never; "snapshot-stale"?: never } | 
/**
 *  A single entry could not be read because the OS denied access. Defined
 *  and ready for v0.2.0: the v0.1.0 walk records such entries and counts
 *  them in [`ScanSummary::skipped_count`](crate::ipc::ScanSummary) rather
 *  than surfacing this per-entry error (AC-11), so a locked subtree never
 *  aborts a scan. Wiring the walk to emit this per entry is a v0.2.0
 *  concern; the code, message, and remediation are pinned here so the IPC
 *  contract is stable before then. Not produced by `run_scan` yet.
 */
({ "permission-denied": {
	path: string,
} }) & { "collision-in-plan"?: never; "collision-on-disk"?: never; "cross-volume-space-insufficient"?: never; "csv-parse"?: never; "cycle-detected"?: never; "db-corrupt-recovered"?: never; "db-migration-failed"?: never; "illegal-component"?: never; "junction-skipped"?: never; "path-too-long"?: never; "reserved-name"?: never; "root-not-directory"?: never; "root-not-found"?: never; "ruleset-invalid"?: never; "scan-failed"?: never; "settings-failed"?: never; "snapshot-stale"?: never } | 
/**
 *  A junction or reparse point was recorded but deliberately not followed
 *  (D-09), so the walk cannot loop through a link back into the tree.
 *  Defined and ready for v0.2.0 on the same footing as
 *  [`PermissionDenied`](AppError::PermissionDenied): the v0.1.0 walk counts
 *  the skip on the summary rather than emitting this per-entry error, and
 *  wiring it per entry is a v0.2.0 concern. Not produced by `run_scan` yet.
 */
({ "junction-skipped": {
	path: string,
} }) & { "collision-in-plan"?: never; "collision-on-disk"?: never; "cross-volume-space-insufficient"?: never; "csv-parse"?: never; "cycle-detected"?: never; "db-corrupt-recovered"?: never; "db-migration-failed"?: never; "illegal-component"?: never; "path-too-long"?: never; "permission-denied"?: never; "reserved-name"?: never; "root-not-directory"?: never; "root-not-found"?: never; "ruleset-invalid"?: never; "scan-failed"?: never; "settings-failed"?: never; "snapshot-stale"?: never } | 
/**
 *  An internal failure while writing the snapshot (a SQLite/transaction
 *  error during the scans/entries write path). The walk itself never fails
 *  this way; this is the DB-side hard-failure end of `run_scan`.
 */
({ "scan-failed": {
	detail: string,
} }) & { "collision-in-plan"?: never; "collision-on-disk"?: never; "cross-volume-space-insufficient"?: never; "csv-parse"?: never; "cycle-detected"?: never; "db-corrupt-recovered"?: never; "db-migration-failed"?: never; "illegal-component"?: never; "junction-skipped"?: never; "path-too-long"?: never; "permission-denied"?: never; "reserved-name"?: never; "root-not-directory"?: never; "root-not-found"?: never; "ruleset-invalid"?: never; "settings-failed"?: never; "snapshot-stale"?: never } | 
/**
 *  A WizTree CSV import (F-102) could not fully parse. `row` is the 1-based
 *  index of the offending data row (the row after the header, preamble
 *  lines not counted), OR `0` reserved for a file-level/structural failure
 *  (the file could not be opened, or no WizTree header line was found at
 *  all) rather than a single bad data row.
 * 
 *  Isolated bad data rows (`row >= 1`) are recovered from: the row is
 *  skipped and the import continues with the rest of the file, so this
 *  variant surfaces as a per-row record the caller collects rather than as
 *  a hard `Err` in that case. A wholly invalid file (`row == 0`) IS a hard
 *  `Err` returned before any `scans` row is written, mirroring
 *  [`AppError::RootNotFound`]'s before-any-write posture.
 */
({ "csv-parse": {
	row: number,
} }) & { "collision-in-plan"?: never; "collision-on-disk"?: never; "cross-volume-space-insufficient"?: never; "cycle-detected"?: never; "db-corrupt-recovered"?: never; "db-migration-failed"?: never; "illegal-component"?: never; "junction-skipped"?: never; "path-too-long"?: never; "permission-denied"?: never; "reserved-name"?: never; "root-not-directory"?: never; "root-not-found"?: never; "ruleset-invalid"?: never; "scan-failed"?: never; "settings-failed"?: never; "snapshot-stale"?: never } | 
/**
 *  A ruleset's JSON body could not be accepted: it is not valid JSON, is
 *  missing a required field, has a field of the wrong type, carries a
 *  `schema_version` this build does not support, or holds an out-of-range
 *  value (for example a series-index width below 1). Returned by
 *  [`crate::ruleset::parse_and_validate`] BEFORE any row is written, so a
 *  bad body is never persisted half-valid (AC-29). `detail` is a
 *  developer-facing explanation; the remediation is the user-facing one.
 */
({ "ruleset-invalid": {
	detail: string,
} }) & { "collision-in-plan"?: never; "collision-on-disk"?: never; "cross-volume-space-insufficient"?: never; "csv-parse"?: never; "cycle-detected"?: never; "db-corrupt-recovered"?: never; "db-migration-failed"?: never; "illegal-component"?: never; "junction-skipped"?: never; "path-too-long"?: never; "permission-denied"?: never; "reserved-name"?: never; "root-not-directory"?: never; "root-not-found"?: never; "scan-failed"?: never; "settings-failed"?: never; "snapshot-stale"?: never } | 
/**
 *  A source path recorded at plan time no longer exists at validation time
 *  (the snapshot went stale). The operation cannot run against a vanished
 *  source.
 */
({ "snapshot-stale": {
	path: string,
} }) & { "collision-in-plan"?: never; "collision-on-disk"?: never; "cross-volume-space-insufficient"?: never; "csv-parse"?: never; "cycle-detected"?: never; "db-corrupt-recovered"?: never; "db-migration-failed"?: never; "illegal-component"?: never; "junction-skipped"?: never; "path-too-long"?: never; "permission-denied"?: never; "reserved-name"?: never; "root-not-directory"?: never; "root-not-found"?: never; "ruleset-invalid"?: never; "scan-failed"?: never; "settings-failed"?: never } | 
/**
 *  Two operations in the same plan produce the same target path (compared
 *  case-insensitively for NTFS), so one would clobber the other.
 */
({ "collision-in-plan": {
	path: string,
} }) & { "collision-on-disk"?: never; "cross-volume-space-insufficient"?: never; "csv-parse"?: never; "cycle-detected"?: never; "db-corrupt-recovered"?: never; "db-migration-failed"?: never; "illegal-component"?: never; "junction-skipped"?: never; "path-too-long"?: never; "permission-denied"?: never; "reserved-name"?: never; "root-not-directory"?: never; "root-not-found"?: never; "ruleset-invalid"?: never; "scan-failed"?: never; "settings-failed"?: never; "snapshot-stale"?: never } | 
/**
 *  An operation's target path already exists on disk (compared
 *  case-insensitively for NTFS) and is not being vacated by the plan.
 */
({ "collision-on-disk": {
	path: string,
} }) & { "collision-in-plan"?: never; "cross-volume-space-insufficient"?: never; "csv-parse"?: never; "cycle-detected"?: never; "db-corrupt-recovered"?: never; "db-migration-failed"?: never; "illegal-component"?: never; "junction-skipped"?: never; "path-too-long"?: never; "permission-denied"?: never; "reserved-name"?: never; "root-not-directory"?: never; "root-not-found"?: never; "ruleset-invalid"?: never; "scan-failed"?: never; "settings-failed"?: never; "snapshot-stale"?: never } | 
/**
 *  A target path exceeds the maximum length even with the Windows
 *  extended-length (`\\?\`) allowance. `length` is the measured character
 *  count.
 */
({ "path-too-long": {
	path: string,
	length: number,
} }) & { "collision-in-plan"?: never; "collision-on-disk"?: never; "cross-volume-space-insufficient"?: never; "csv-parse"?: never; "cycle-detected"?: never; "db-corrupt-recovered"?: never; "db-migration-failed"?: never; "illegal-component"?: never; "junction-skipped"?: never; "permission-denied"?: never; "reserved-name"?: never; "root-not-directory"?: never; "root-not-found"?: never; "ruleset-invalid"?: never; "scan-failed"?: never; "settings-failed"?: never; "snapshot-stale"?: never } | 
/**
 *  A path component is not a legal filesystem name (an illegal character, or
 *  a trailing dot/space). This is the backstop to the F-304 name normalizer.
 */
({ "illegal-component": {
	path: string,
	component: string,
} }) & { "collision-in-plan"?: never; "collision-on-disk"?: never; "cross-volume-space-insufficient"?: never; "csv-parse"?: never; "cycle-detected"?: never; "db-corrupt-recovered"?: never; "db-migration-failed"?: never; "junction-skipped"?: never; "path-too-long"?: never; "permission-denied"?: never; "reserved-name"?: never; "root-not-directory"?: never; "root-not-found"?: never; "ruleset-invalid"?: never; "scan-failed"?: never; "settings-failed"?: never; "snapshot-stale"?: never } | 
/**
 *  A path component is (or begins with) a reserved Windows device name
 *  (CON, PRN, AUX, NUL, COM1-9, LPT1-9). Backstop to F-304.
 */
({ "reserved-name": {
	path: string,
	component: string,
} }) & { "collision-in-plan"?: never; "collision-on-disk"?: never; "cross-volume-space-insufficient"?: never; "csv-parse"?: never; "cycle-detected"?: never; "db-corrupt-recovered"?: never; "db-migration-failed"?: never; "illegal-component"?: never; "junction-skipped"?: never; "path-too-long"?: never; "permission-denied"?: never; "root-not-directory"?: never; "root-not-found"?: never; "ruleset-invalid"?: never; "scan-failed"?: never; "settings-failed"?: never; "snapshot-stale"?: never } | 
/**
 *  The cross-volume operations targeting `volume` sum to more bytes
 *  (`needed`) than the volume has free (`available`), so the
 *  copy+verify+delete moves cannot all complete.
 */
({ "cross-volume-space-insufficient": {
	volume: string,
	needed: number,
	available: number,
} }) & { "collision-in-plan"?: never; "collision-on-disk"?: never; "csv-parse"?: never; "cycle-detected"?: never; "db-corrupt-recovered"?: never; "db-migration-failed"?: never; "illegal-component"?: never; "junction-skipped"?: never; "path-too-long"?: never; "permission-denied"?: never; "reserved-name"?: never; "root-not-directory"?: never; "root-not-found"?: never; "ruleset-invalid"?: never; "scan-failed"?: never; "settings-failed"?: never; "snapshot-stale"?: never } | 
/**
 *  An operation would move a source into its own subtree (target lies inside
 *  source), which is a cycle no filesystem can perform.
 */
({ "cycle-detected": {
	source_path: string,
	target_path: string,
} }) & { "collision-in-plan"?: never; "collision-on-disk"?: never; "cross-volume-space-insufficient"?: never; "csv-parse"?: never; "db-corrupt-recovered"?: never; "db-migration-failed"?: never; "illegal-component"?: never; "junction-skipped"?: never; "path-too-long"?: never; "permission-denied"?: never; "reserved-name"?: never; "root-not-directory"?: never; "root-not-found"?: never; "ruleset-invalid"?: never; "scan-failed"?: never; "settings-failed"?: never; "snapshot-stale"?: never } | 
/**
 *  A proceed/apply was requested but no operation is in the `approved`
 *  state, so there is nothing to do. Defined for the v0.5.0 apply path;
 *  v0.3.0 only plans and validates.
 */
"nothing-approved";

/**
 *  The singleton application settings (F-803), the wire form of the one
 *  `settings` row (migrations 0001/0002/0003). Returned by `settings_get` and
 *  accepted by `settings_set`.
 * 
 *  Field-to-column mapping and the one deliberate name divergence:
 * 
 *  - `library_root` -> `settings.library_root`. The sanctioned scan root the
 *    backend re-allows at startup (FD-29, F-909). `None` means no library is
 *    configured yet, which is exactly how the shell detects first-run.
 *  - `set_aside_root` -> `settings.quarantine_root`. The field is named for the
 *    plain-language "set aside" vocabulary the UI uses (FD-31), while the column
 *    and every internal type keep "quarantine". The IPC boundary is the seam
 *    where the internal term becomes the family-facing one, so the crossing
 *    payload speaks the user's vocabulary and the storage keeps the engine's.
 *  - `reports_root` -> `settings.reports_root`. Optional Reports-folder override
 *    (F-1002); `None` uses the default beside the app data.
 *  - `theme` -> `settings.theme`. `"day"` or `"evening"` (FD-09). Always a valid
 *    theme string: `get_settings` normalizes any unexpected stored value back to
 *    `"day"` so the UI never receives a theme it cannot render.
 *  - `scan_retention_count` -> `settings.scan_retention_count` (FD-20, AC-35).
 * 
 *  A root stored as an empty string is normalized to `None` on read, and a
 *  `Some("")` is written as SQL NULL, so "unset" has one representation.
 */
export type AppSettings = {
	/**  The sanctioned library scan root (FD-29, F-909); `None` until first-run. */
	library_root: string | null,
	/**
	 *  Where set-aside items land (the `quarantine_root` column, FD-31); `None`
	 *  uses the default beside the app data.
	 */
	set_aside_root: string | null,
	/**  Optional override for the Reports folder (F-1002); `None` uses the default. */
	reports_root: string | null,
	/**  UI theme, `"day"` or `"evening"` (FD-09). Never any other value on read. */
	theme: string,
	/**  Snapshot retention: keep the last N scans (FD-20, AC-35). Default 10. */
	scan_retention_count: number,
};

/**
 *  One example book on the "Worth a look first" shelf (F-902, v0.4.0 Phase 4,
 *  design-system Section 4.6). `entry_id` names a book WITHIN the snapshot that
 *  produced the enclosing [`LibraryOverview`] (its `scan_id`), so the frontend
 *  can pass `(scan_id, entry_id)` straight to `cover_get` for the book's cover
 *  - the same snapshot-scoped identity [`EntryRow`] already uses.
 * 
 *  `title` is never absent (a book the shelf shows always parsed a title, own
 *  or derived); `author` is [`None`] when no author could be read, which the
 *  frontend's `Cover`/`FallbackTile` already render gracefully (AC-23).
 */
export type BookExample = {
	entry_id: number,
	title: string,
	author: string | null,
	reason: BookReason,
};

/**
 *  The plain-language "why this book is worth a look" chip under one
 *  [`BookExample`] (design-system Section 4.6 `.bookslot` / `.why`).
 */
export type BookReason = {
	kind: ReasonKind,
	/**
	 *  Plain-language chip text, e.g. "loose file", "messy name",
	 *  "7 books, 1 folder", "2 copies". Never a raw class/rule id (Section 6).
	 */
	text: string,
};

/**
 *  A per-class metric: how many folders carry the class, and how many bytes are
 *  attributed to it. `folder_count` is in folders; `byte_total` is in bytes
 *  (the units are stated by the field names, FD-08).
 */
export type ClassMetric = {
	class: FolderClass,
	folder_count: number,
	byte_total: number,
};

/**
 *  One book's cover art (F-907, v0.4.0 Phase 3), the wire form returned by the
 *  `cover_get` command. `None` from that command means "no cover" and the
 *  frontend renders the deterministic fallback tile instead (AC-23).
 * 
 *  The bytes cross IPC as base64 (`data:` payload), not as a filesystem path and
 *  not as a raw byte array: base64 keeps the payload compact and, decisively,
 *  means the WebView is handed already-read image data over typed IPC rather than
 *  any filesystem or asset-protocol scope. The library root never becomes
 *  WebView-readable (FD-29). The frontend composes `data:${mime};base64,${base64}`
 *  as the `<img>` source.
 * 
 *  `mime` is sniffed from the bytes (e.g. `image/jpeg`, `image/png`), so a
 *  mislabeled sidecar or corrupt frame is rejected before it reaches here (the
 *  book then shows the fallback tile). The bytes are the raw, UNDECODED image as
 *  stored in the file (plan T-11 defers decoding/downscaling).
 */
export type CoverImage = {
	/**  The image mime type, sniffed from the bytes (e.g. `image/jpeg`). */
	mime: string,
	/**  Standard base64 (RFC 4648, `=`-padded) of the raw image bytes. */
	base64: string,
};

/**
 *  Returned by the `db_status` command: the wire form of the startup
 *  [`crate::db::DbOpenOutcome`] (P2), reporting whether corrupt-DB recovery ran.
 * 
 *  [`crate::db::DbOpenOutcome`] is a startup-internal Rust type (it carries a
 *  `PathBuf`) and is deliberately NOT part of the IPC contract; the shell maps it
 *  to this serde/specta payload once, at the boundary. `recovered` is true
 *  exactly when the existing database was unreadable and was reset; when true,
 *  `backup_path` is where the prior database was preserved (the human-readable
 *  stored form), else `None`.
 */
export type DbStatus = {
	/**
	 *  True exactly when startup found a corrupt/unopenable database and reset it
	 *  (see [`crate::db::DbOpenOutcome::Recovered`]).
	 */
	recovered: boolean,
	/**  Where the corrupt database was preserved, when `recovered`; else `None`. */
	backup_path: string | null,
};

/**
 *  One persisted `entries` row (F-101 / F-105), read back for the tracer.
 * 
 *  The shape mirrors the `entries` table one-to-one. `parent_id` is the logical
 *  tree edge (the `entries.id` of the containing directory), `None` for the
 *  scan root. `kind` is `"file"` or `"dir"`; `file_class` is the F-103 class
 *  string for files and `None` for directories. `path` is the stored,
 *  human-readable full path (no `\\?\` prefix). `mtime` is ISO-8601 UTC, or
 *  `None` when the entry could not be stat'd.
 */
export type EntryRow = {
	/**  `entries.id` (assigned at insertion). */
	id: number,
	/**  The owning snapshot (`scans.id`). */
	scan_id: number,
	/**  Logical parent `entries.id`; `None` for the scan root. */
	parent_id: number | null,
	/**  Full path, stored form (no `\\?\` prefix). */
	path: string,
	/**  Final path component (file or directory name). */
	name: string,
	/**  `"file"` or `"dir"`. */
	kind: string,
	/**  F-103 file class for files (`audio`, `video`, ...); `None` for dirs. */
	file_class: string | null,
	/**  Size in bytes; 0 for directories and unstatable entries. */
	size: number,
	/**  Modification time (ISO-8601 UTC); `None` when unavailable. */
	mtime: string | null,
	/**  Depth below the scan root (root is 0). */
	depth: number,
};

/**
 *  The nine F-201 folder classes (the Codex taxonomy plus `docs-resources`).
 *  [`FolderClass::as_str`] is the stable kebab-case string used in evidence,
 *  snapshots, and (later) IPC; serialization uses the same string.
 * 
 *  Derives `serde`/`specta::Type` (v0.4.0 Phase 4, F-902 library home): the
 *  health metrics this class feeds into (`HealthMetrics`, `crate::classify::metrics`)
 *  now cross the IPC boundary inside `LibraryOverview` (`crate::ipc`), so this
 *  type must itself be wire-ready. `#[serde(rename_all = "kebab-case")]`
 *  reproduces exactly the strings [`FolderClass::as_str`] already returns (e.g.
 *  `SeriesContainer` -> `"series-container"`), so the wire format is unchanged
 *  from the hand-written `Serialize` impl this replaces.
 */
export type FolderClass = 
/**  One book's audio (leaf folder of audio, or a disc-split single book). */
"book" | 
/**  A folder whose book-like children cohere into one author/series. */
"series-container" | 
/**  A collection of distinct books: a genre shelf, source pack, or list. */
"pack-container" | 
/**  A staging area (`_sort`, `_process`). */
"staging" | 
/**  Direct audio files AND child folders together. */
"mixed" | 
/**  Several complete books sitting as sibling audio files (F-203). */
"multi-book-suspect" | 
/**  No audio anywhere beneath and no non-audio content either. */
"empty" | 
/**  Non-audio content only (ebooks / images / release info), no audio. */
"docs-resources" | 
/**
 *  Not auto-classifiable, or FD-17 non-book media (video / comics / radio
 *  play). A first-class outcome, never an error.
 */
"manual-review";

/**
 *  The home's "good news" line (design-system Section 4, `.goodline`): what is
 *  ALREADY tidy, stated in the same sentence-with-a-unit register as every
 *  other home number (FD-08, AC-7). Every field is a plain count/byte total
 *  read from the current snapshot's [`HealthMetrics`], never a hardcoded
 *  sample (FD-27).
 */
export type GoodNews = {
	already_tidy_books: number,
	series_shelved: number,
	empty_folders: number,
	duplicate_groups: number,
	duplicate_bytes: number,
};

/**
 *  The full health report: per-class metrics (all nine classes, always present,
 *  zeroed where a class is absent), per-problem metrics, and the library total
 *  in bytes.
 */
export type HealthMetrics = {
	per_class: ClassMetric[],
	problems: ProblemMetric[],
	total_bytes: number,
};

/**  Typed `job:completed` event, emitted when a spawned scan finishes cleanly. */
export type JobCompleted = JobCompletedPayload;

/**
 *  Payload of the `job:completed` event, emitted when a spawned scan finishes
 *  successfully. Carries the originating `job_id` and the `scan_id` of the
 *  snapshot written, so the tracer can read the entries back.
 */
export type JobCompletedPayload = {
	/**  The `jobs.id` returned earlier by `scan_start`. */
	job_id: number,
	/**  The `scans.id` of the snapshot the completed scan wrote. */
	scan_id: number,
};

/**  Typed `job:failed` event, emitted when a spawned scan errors. */
export type JobFailed = JobFailedPayload;

/**
 *  Payload of the `job:failed` event, emitted when a spawned scan errors. Carries
 *  the originating `job_id` and the stable machine `code` from
 *  [`AppError::code`], so the frontend can key off the same codes the command
 *  results use.
 */
export type JobFailedPayload = {
	/**  The `jobs.id` returned earlier by `scan_start`. */
	job_id: number,
	/**  The stable kebab-case error code (equals [`AppError::code`]). */
	code: string,
};

/**
 *  Typed `job:progress` event.
 * 
 *  DEFINED but NEVER EMITTED in the v0.1.0 spine (this phase's brief): the spine
 *  scan is one spawned unit with no progress reporting or cancellation. It is
 *  collected into the `tauri_specta::Builder` alongside the other two so the
 *  generated bindings surface freezes the whole job-event contract now; a later
 *  release adds the emitter as an additive change. There is deliberately no
 *  `emit_*` helper for it here, precisely because nothing emits it yet.
 */
export type JobProgress = JobProgressPayload;

/**
 *  Payload of the `job:progress` event.
 * 
 *  Frozen NOW so the IPC contract is complete, even though the v0.1.0 spine
 *  NEVER emits it: the spine scan is a single spawned unit with no progress
 *  reporting or cancellation (this phase's brief). Wiring an emitter is a later
 *  release's concern; pinning the shape here means adding progress later is an
 *  additive change that does not perturb the frozen bindings surface.
 */
export type JobProgressPayload = {
	/**  The `jobs.id` this progress update belongs to. */
	job_id: number,
	/**  Units of work completed so far. */
	done: number,
	/**
	 *  Best-known total units, or `None` when the total is not yet known
	 *  (an indeterminate phase).
	 */
	total_estimate: number | null,
	/**
	 *  A short human-readable label for the current step (for example a path or
	 *  stage name).
	 */
	current_label: string,
};

/**
 *  Returned by the `scan_start` command the instant a scan is accepted (F-104).
 * 
 *  `scan_start` inserts a `running` `jobs` row, spawns the scan on the async
 *  runtime, and returns this immediately; the caller then waits for the
 *  [`JobCompletedPayload`] / [`JobFailedPayload`] event carrying the same
 *  `job_id`. This decouples the long-running scan from the IPC call.
 */
export type JobStarted = {
	/**
	 *  `jobs.id` of the row created for this scan; correlates the later
	 *  `job:completed` / `job:failed` event back to this call.
	 */
	job_id: number,
};

/**
 *  The full library home payload (F-902, v0.4.0 Phase 4), returned by the
 *  `classify_overview` command. [`None`] from that command means no scan has
 *  ever completed - the honest pre-first-scan state (AC-6) - in which case the
 *  frontend shows the empty-library state and the scan affordance rather than
 *  any of this shape's zeroed fields (a real zero and "never scanned" must
 *  never be confused).
 * 
 *  Every count and byte figure here is computed from the snapshot named by
 *  `scan_id` at render time (AC-7): nothing is a literal/sample value. See
 *  [`crate::classify::build_overview`] for the derivation.
 */
export type LibraryOverview = {
	/**
	 *  The snapshot this overview was computed from (`scans.id`); the frontend
	 *  passes this alongside a [`BookExample::entry_id`] to `cover_get`.
	 */
	scan_id: number,
	/**
	 *  Every book the library holds: one per `book`-class folder (a disc-split
	 *  book still counts once) plus one per loose-root audio file plus the
	 *  distinct titles F-203 found inside each `multi-book-suspect` folder.
	 */
	total_books: number,
	/**
	 *  Sum of file sizes across the whole snapshot (equals
	 *  [`HealthMetrics::total_bytes`]).
	 */
	total_bytes: number,
	/**
	 *  How many of `total_books` carry at least one "worth a look" problem
	 *  (loose file, messy folder name, a multi-book/box-set folder, or a
	 *  duplicate copy). `total_books - needs_tidy_books` is already tidy.
	 */
	needs_tidy_books: number,
	/**
	 *  A bounded set of example books for the "Worth a look first" shelf
	 *  (design-system Section 4.6-4.7): curated examples, not the exhaustive
	 *  list - the full list is the Phase 5 review surface and the exported
	 *  report (D-16).
	 */
	worth_a_look: BookExample[],
	/**  Real series containers on the shelves (design-system Section 4.8). */
	series: SeriesCluster[],
	good_news: GoodNews,
	/**
	 *  The full per-class/per-problem health report this overview was built
	 *  from, so the sidebar's Duplicates badge (FD-08 GROUP count) and any
	 *  other per-group count reads the same numbers the home prose does.
	 */
	metrics: HealthMetrics,
};

/**
 *  The quantity a metric counts (FD-08: no bare number without its unit).
 * 
 *  Derives `serde`/`specta::Type` (v0.4.0 Phase 4): `HealthMetrics` crosses the
 *  IPC boundary inside `LibraryOverview` (`crate::ipc`), so every type it
 *  contains must be wire-ready. `#[serde(rename_all = "lowercase")]` reproduces
 *  exactly the strings [`MetricUnit::as_str`] already returns, so the wire
 *  format is unchanged from the hand-written `Serialize` impl this replaces.
 */
export type MetricUnit = "folders" | "files" | "bytes" | 
/**  Duplicate GROUPS (one book, N copies = one group; FD-08). */
"groups";

/**
 *  A per-problem metric, carrying its own explicit unit (FD-08). `count` is in
 *  the stated `unit`; `byte_total` is always bytes (0 where a size is not
 *  meaningful for the problem, e.g. deep nesting).
 */
export type ProblemMetric = {
	/**
	 *  Stable kebab-case problem id (e.g. `"loose-root-books"`). `String` (not
	 *  `&'static str`) so this struct can derive `Deserialize` for the IPC
	 *  contract test (v0.4.0 Phase 4): every value this crate ever constructs
	 *  is still one of the fixed string-literal ids below.
	 */
	problem: string,
	unit: MetricUnit,
	count: number,
	byte_total: number,
};

/**
 *  Which register a [`BookReason`] chip reads in (design-system Section 4.6):
 *  a soft, tidy-adjacent note (`warn`, e.g. "loose file", "messy name") versus
 *  a structural flag that needs a decision (`alert`, e.g. "7 books, 1 folder",
 *  "2 copies"). Icon-plus-label always accompanies the kind; color is never
 *  the only signal (Section 8 accessibility).
 */
export type ReasonKind = "warn" | "alert";

/**
 *  One series cluster on the "Series on your shelves" shelf (design-system
 *  Section 4.8). `name` is the series name (falling back to the container
 *  folder's own name when no series field parsed, so a real series-container
 *  never disappears from the shelf for want of a label); `book_count` is the
 *  number of book-like children the classifier folded into this container
 *  (`Evidence::book_children`).
 */
export type SeriesCluster = {
	name: string,
	author: string | null,
	book_count: number,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

