//! Integration tests for F-1001 (activity log), v0.2.0 Phase 6: AC-1001.1,
//! AC-1001.2.
//!
//! Covers the three hooked entry points end to end (scan, CSV import,
//! classify) rather than re-testing `append_activity` itself (see the unit
//! tests in `src/db/activity.rs` for that): one row per run, a failure row
//! carrying its error code, and no prior row ever mutated by a later append.

use abo_core::classify::{run_classify, ClassifyInput};
use abo_core::db::open_db;
use abo_core::error::AppError;
use abo_core::parse::extract::NodeKind;
use abo_core::scan::{run_csv_import, run_scan};
use sqlx::{Row, SqlitePool};
use tempfile::TempDir;

async fn fresh_pool() -> (TempDir, SqlitePool) {
    let dir = TempDir::new().expect("db tempdir");
    let (pool, _) = open_db(dir.path()).await.expect("open_db");
    (dir, pool)
}

async fn activity_rows(pool: &SqlitePool) -> Vec<(String, String, String)> {
    sqlx::query("SELECT action, outcome, created_at FROM activity_records ORDER BY id")
        .fetch_all(pool)
        .await
        .expect("fetch activity_records")
        .into_iter()
        .map(|row| {
            (
                row.get::<String, _>("action"),
                row.get::<String, _>("outcome"),
                row.get::<String, _>("created_at"),
            )
        })
        .collect()
}

/// AC-1001.1: a successful live scan appends exactly one `activity_records`
/// row, action `"scan"`, outcome `"succeeded"`.
#[tokio::test]
async fn successful_scan_appends_one_succeeded_row() {
    let (_db, pool) = fresh_pool().await;
    let tree = TempDir::new().expect("scan tree tempdir");
    std::fs::write(tree.path().join("book.m4b"), b"audio").unwrap();

    run_scan(&pool, tree.path()).await.expect("scan runs");

    let rows = activity_rows(&pool).await;
    assert_eq!(rows.len(), 1, "one row for the one scan run");
    assert_eq!(rows[0].0, "scan");
    assert_eq!(rows[0].1, "succeeded");
}

/// AC-1001.2: a scan against a nonexistent root fails before any `scans` row
/// is written, but the activity log still records the failed run with the
/// `root-not-found` machine error code.
#[tokio::test]
async fn failed_scan_records_error_code() {
    let (_db, pool) = fresh_pool().await;
    let missing_root = std::env::temp_dir().join("abo-activity-log-test-does-not-exist");

    let result = run_scan(&pool, &missing_root).await;
    assert!(matches!(result, Err(AppError::RootNotFound { .. })));

    let rows = activity_rows(&pool).await;
    assert_eq!(rows.len(), 1, "the failed run is still logged once");
    assert_eq!(rows[0].0, "scan");
    assert_eq!(rows[0].1, "failed:root-not-found");
}

/// AC-1001.1: a successful WizTree CSV import appends exactly one
/// `activity_records` row, action `"csv-import"`, outcome `"succeeded"`.
#[tokio::test]
async fn successful_csv_import_appends_one_succeeded_row() {
    let (_db, pool) = fresh_pool().await;
    let csv_dir = TempDir::new().expect("csv tempdir");
    let csv_path = csv_dir.path().join("sample.csv");
    let body = "Generated by WizTree 4.30 3/25/2026 8:54:06 AM\r\n\
                File Name,Size,Allocated,Modified,Attributes,Files,Folders,FOLDERSIZE,FOLDERALLOCATED,DRIVECAPACITY,FREESPACE,USEDSPACE,RESERVEDSPACE\r\n\
                \"E:\\Lib\\\",100,104,2026/01/01 00:00:00,0,1,0,100,104,100,100,100,100\r\n\
                \"E:\\Lib\\root.m4b\",100,104,2026/01/02 00:00:00,32,0,0,100,104\r\n";
    std::fs::write(&csv_path, body).expect("write fixture csv");

    run_csv_import(&pool, &csv_path)
        .await
        .expect("csv import runs");

    let rows = activity_rows(&pool).await;
    assert_eq!(rows.len(), 1, "one row for the one csv-import run");
    assert_eq!(rows[0].0, "csv-import");
    assert_eq!(rows[0].1, "succeeded");
}

/// AC-1001.2: a wholly invalid CSV file fails with `csv-parse`, and the
/// activity log records the failure with that machine error code.
#[tokio::test]
async fn failed_csv_import_records_error_code() {
    let (_db, pool) = fresh_pool().await;
    let csv_dir = TempDir::new().expect("csv tempdir");
    let csv_path = csv_dir.path().join("not-wiztree.csv");
    std::fs::write(&csv_path, "nope,not,a,wiztree,file\r\n").expect("write junk file");

    let result = run_csv_import(&pool, &csv_path).await;
    assert!(matches!(result, Err(AppError::CsvParse { row: 0 })));

    let rows = activity_rows(&pool).await;
    assert_eq!(rows.len(), 1, "the failed run is still logged once");
    assert_eq!(rows[0].0, "csv-import");
    assert_eq!(rows[0].1, "failed:csv-parse");
}

/// AC-1001.1: a classify run appends exactly one `activity_records` row,
/// action `"classify"`. Parse (F-301..304) runs INSIDE this same call
/// (`classify` consumes `parse::extract` internally, see `db::activity`'s
/// module doc), so no separate parse row is expected.
#[tokio::test]
async fn classify_run_appends_one_row_covering_parse() {
    let (_db, pool) = fresh_pool().await;
    let entries = vec![ClassifyInput {
        id: 0,
        parent: None,
        name: "Some Book by Some Author".to_string(),
        kind: NodeKind::Folder,
        file_class: None,
        size: 0,
    }];

    run_classify(&pool, &entries).await.expect("classify runs");

    let rows = activity_rows(&pool).await;
    assert_eq!(
        rows.len(),
        1,
        "one row for the classify run; no separate parse row exists"
    );
    assert_eq!(rows[0].0, "classify");
    assert_eq!(rows[0].1, "succeeded");
}

/// AC-1001.2 (append-only): three runs across all three hooked entry points
/// append three distinct rows in order, and none of the earlier rows is ever
/// mutated by a later append.
#[tokio::test]
async fn multiple_runs_append_without_mutating_prior_rows() {
    let (_db, pool) = fresh_pool().await;

    // Run 1: a successful scan.
    let tree = TempDir::new().expect("scan tree tempdir");
    std::fs::write(tree.path().join("book.m4b"), b"audio").unwrap();
    run_scan(&pool, tree.path()).await.expect("scan runs");
    let after_first = activity_rows(&pool).await;
    assert_eq!(after_first.len(), 1);

    // Run 2: a failed csv import.
    let csv_dir = TempDir::new().expect("csv tempdir");
    let csv_path = csv_dir.path().join("not-wiztree.csv");
    std::fs::write(&csv_path, "nope\r\n").expect("write junk file");
    let _ = run_csv_import(&pool, &csv_path).await;
    let after_second = activity_rows(&pool).await;
    assert_eq!(after_second.len(), 2);
    assert_eq!(
        after_second[0], after_first[0],
        "the first row must be unchanged after the second append"
    );

    // Run 3: a classify run.
    let entries = vec![ClassifyInput {
        id: 0,
        parent: None,
        name: "Whatever".to_string(),
        kind: NodeKind::Folder,
        file_class: None,
        size: 0,
    }];
    run_classify(&pool, &entries).await.expect("classify runs");
    let after_third = activity_rows(&pool).await;
    assert_eq!(after_third.len(), 3);
    assert_eq!(
        after_third[0], after_second[0],
        "the first row must still be unchanged after the third append"
    );
    assert_eq!(
        after_third[1], after_second[1],
        "the second row must still be unchanged after the third append"
    );

    assert_eq!(
        after_third
            .iter()
            .map(|(action, _, _)| action.as_str())
            .collect::<Vec<_>>(),
        vec!["scan", "csv-import", "classify"],
        "rows appear in append order"
    );
}
