//! Integration tests for the Phase 3 WizTree CSV import (F-102): AC-102.1,
//! AC-102.2, AC-102.3.
//!
//! `import_synthetic_csv_produces_valid_snapshot` runs on every OS (the CI
//! test job runs ubuntu + windows): it is pure text in, DB rows out, with no
//! dependency on the host's own path-separator convention (see
//! `crate::scan::csv_import`'s module doc). `import_parity_with_live_scan_of_
//! fixture_library` (AC-102.2) IS Windows-only: it round-trips a live scan's
//! OWN host-native paths through a constructed WizTree CSV, which is only a
//! meaningful comparison when those paths are the Windows-backslash form
//! WizTree itself always emits. `import_real_wiztree_2026_03_25_csv` is
//! `#[ignore]`d (the real file lives under `_local/`, never committed, so CI
//! never has it) and is run locally on demand: `cargo test -p abo-core
//! --test csv_import -- --ignored`.

use std::path::Path;

use abo_core::db::open_db;
use abo_core::scan::{get_scan_entries, run_csv_import};
use sqlx::SqlitePool;
use tempfile::TempDir;

/// A fresh, migrated database in its own temp dir (kept alive by the returned
/// `TempDir`), matching the `tests/scan.rs` convention.
async fn fresh_pool() -> (TempDir, SqlitePool) {
    let dir = TempDir::new().expect("db tempdir");
    let (pool, _) = open_db(dir.path()).await.expect("open_db");
    (dir, pool)
}

const PREAMBLE_AND_HEADER: &str =
    "Generated by WizTree 4.30 3/25/2026 8:54:06 AM (You can hide this message by making a donation)\r\n\
     File Name,Size,Allocated,Modified,Attributes,Files,Folders,FOLDERSIZE,FOLDERALLOCATED,DRIVECAPACITY,FREESPACE,USEDSPACE,RESERVEDSPACE\r\n";

/// AC-102.1: importing a small hand-built WizTree CSV produces a valid
/// snapshot flagged `source = csv` with parent linkage reconstructed from the
/// path column, sizes/kinds/classes/depths matching the CSV's contents.
#[tokio::test]
async fn import_synthetic_csv_produces_valid_snapshot() {
    let (_db, pool) = fresh_pool().await;
    let csv_dir = TempDir::new().expect("csv tempdir");
    let csv_path = csv_dir.path().join("sample.csv");

    let body = "\"E:\\Lib\\\",300,304,2026/01/01 00:00:00,0,3,1,300,304,100,100,100,100\r\n\
                \"E:\\Lib\\Sub\\\",200,204,2026/01/02 00:00:00,16,1,0,200,204\r\n\
                \"E:\\Lib\\root.m4b\",100,104,2026/01/03 00:00:00,32,0,0,100,104\r\n\
                \"E:\\Lib\\Sub\\nested.mp3\",200,204,2026/01/04 00:00:00,32,0,0,200,204\r\n\
                \"E:\\Lib\\cover.jpg\",50,52,2026/01/05 00:00:00,32,0,0,50,52\r\n";
    std::fs::write(&csv_path, format!("{PREAMBLE_AND_HEADER}{body}")).expect("write fixture csv");

    let summary = run_csv_import(&pool, &csv_path).await.expect("csv import");
    assert_eq!(summary.status, "completed");
    assert_eq!(summary.skipped_count, 0, "clean fixture skips nothing");
    assert_eq!(summary.entry_count, 5);
    assert_eq!(
        summary.total_bytes,
        100 + 200 + 50,
        "sum of the 3 file sizes"
    );
    assert_eq!(summary.root_path, r"E:\Lib");

    // The `scans` row is flagged `source = csv` (AC-102.1).
    let (source,): (String,) = sqlx::query_as("SELECT source FROM scans WHERE id = ?")
        .bind(summary.scan_id)
        .fetch_one(&pool)
        .await
        .expect("fetch source");
    assert_eq!(source, "csv");

    let entries = get_scan_entries(&pool, summary.scan_id)
        .await
        .expect("read entries");
    assert_eq!(entries.len(), 5);

    let by_name = |name: &str| {
        entries
            .iter()
            .find(|e| e.name == name)
            .unwrap_or_else(|| panic!("missing entry {name}"))
    };

    // Parent linkage reconstructed from the path column: exactly the root
    // lacks a parent, and every other entry's parent_id resolves to a real
    // row in the same snapshot (AC-102.1).
    let root = by_name("Lib");
    assert_eq!(root.kind, "dir");
    assert_eq!(root.depth, 0);
    assert_eq!(root.parent_id, None, "the root has no parent");
    assert!(root.file_class.is_none());

    let sub = by_name("Sub");
    assert_eq!(sub.kind, "dir");
    assert_eq!(sub.depth, 1);
    assert_eq!(sub.parent_id, Some(root.id));

    let root_file = by_name("root.m4b");
    assert_eq!(root_file.kind, "file");
    assert_eq!(root_file.file_class.as_deref(), Some("audio"));
    assert_eq!(root_file.size, 100);
    assert_eq!(root_file.parent_id, Some(root.id));

    let nested = by_name("nested.mp3");
    assert_eq!(nested.depth, 2);
    assert_eq!(nested.file_class.as_deref(), Some("audio"));
    assert_eq!(nested.parent_id, Some(sub.id));

    let cover = by_name("cover.jpg");
    assert_eq!(cover.file_class.as_deref(), Some("image"));
    assert_eq!(cover.parent_id, Some(root.id));

    let no_parent = entries.iter().filter(|e| e.parent_id.is_none()).count();
    assert_eq!(no_parent, 1, "only the root lacks a parent");
    let ids: std::collections::HashSet<i64> = entries.iter().map(|e| e.id).collect();
    for e in entries.iter().filter(|e| e.parent_id.is_some()) {
        assert!(
            ids.contains(&e.parent_id.unwrap()),
            "parent_id of {} must reference an entry in the snapshot",
            e.name
        );
    }
}

/// AC-102.3: a CSV with one malformed row still produces a snapshot for the
/// rest, and the caller-visible `skipped_count` reflects the one recovered
/// row (the row's exact index is unit-tested directly against
/// `parse_wiztree_csv` in `src/scan/csv_import.rs`).
#[tokio::test]
async fn import_recovers_from_one_malformed_row() {
    let (_db, pool) = fresh_pool().await;
    let csv_dir = TempDir::new().expect("csv tempdir");
    let csv_path = csv_dir.path().join("sample.csv");

    let body = "\"E:\\Lib\\\",300,304,2026/01/01 00:00:00,0,2,0,300,304,100,100,100,100\r\n\
                \"E:\\Lib\\good.mp3\",100,104,2026/01/02 00:00:00,32,0,0,100,104\r\n\
                \"E:\\Lib\\bad.mp3\",NOTANUMBER,104,2026/01/03 00:00:00,32,0,0,100,104\r\n";
    std::fs::write(&csv_path, format!("{PREAMBLE_AND_HEADER}{body}")).expect("write fixture csv");

    let summary = run_csv_import(&pool, &csv_path).await.expect("csv import");
    assert_eq!(summary.status, "completed");
    assert_eq!(
        summary.skipped_count, 1,
        "the one bad row is counted, not fatal"
    );
    assert_eq!(summary.entry_count, 2, "root + the one good file");

    let entries = get_scan_entries(&pool, summary.scan_id)
        .await
        .expect("read entries");
    assert!(entries.iter().any(|e| e.name == "good.mp3"));
    assert!(!entries.iter().any(|e| e.name == "bad.mp3"));
}

/// A wholly invalid file (no WizTree header at all) fails cleanly and writes
/// no `scans` row, mirroring `run_scan`'s bad-root posture.
#[tokio::test]
async fn import_wholly_invalid_file_writes_no_scan_row() {
    use abo_core::error::AppError;

    let (_db, pool) = fresh_pool().await;
    let csv_dir = TempDir::new().expect("csv tempdir");
    let csv_path = csv_dir.path().join("not-wiztree.csv");
    std::fs::write(&csv_path, "nope,not,a,wiztree,file\r\n").expect("write junk file");

    let result = run_csv_import(&pool, &csv_path).await;
    match result {
        Err(AppError::CsvParse { row: 0 }) => {}
        other => panic!("expected CsvParse{{row: 0}}, got {other:?}"),
    }

    let (count,): (i64,) = sqlx::query_as("SELECT COUNT(*) FROM scans")
        .fetch_one(&pool)
        .await
        .unwrap();
    assert_eq!(count, 0, "an invalid CSV writes no scans row");
}

// ---------------------------------------------------------------------------
// AC-102.2: parity between a live scan and a CSV import of an equivalent tree.
// ---------------------------------------------------------------------------

/// Convert the walker's ISO-8601 UTC mtime (`YYYY-MM-DDTHH:MM:SSZ`) back into
/// WizTree's `Modified` shape (`YYYY/MM/DD HH:MM:SS`), the reverse of
/// `crate::scan::csv_import::reformat_modified`. Test-only: only needs to
/// round-trip the exact shape the walker itself produces.
fn to_wiztree_modified(iso: &str) -> String {
    let date = &iso[0..10].replace('-', "/");
    let time = &iso[11..19];
    format!("{date} {time}")
}

/// Quote a `File Name` field WizTree-style (wrap in `"`; WizTree paths never
/// contain a literal `"`, so no escaping is needed for this test's fixtures).
fn quote(s: &str) -> String {
    format!("\"{s}\"")
}

/// AC-102.2: scan the P1 generated fixture library live, construct an
/// equivalent WizTree CSV from that exact snapshot's own entries, import it,
/// and compare the two entries tables (paths, kinds, sizes, depths, classes).
/// Windows-only: this constructs WizTree rows from the live scan's OWN
/// host-native paths, which is only a like-for-like comparison when those
/// paths are the Windows-backslash form WizTree always emits (see this file's
/// module doc and `crate::scan::csv_import`'s cross-platform-path section).
#[cfg(windows)]
#[tokio::test]
async fn import_parity_with_live_scan_of_fixture_library() {
    use abo_core::fixtures::{generate, standard_library_manifest};
    use abo_core::scan::run_scan;

    let (_db, pool) = fresh_pool().await;
    let tree = TempDir::new().expect("fixture tempdir");
    generate(&standard_library_manifest(), tree.path()).expect("generate fixtures");

    let live_summary = run_scan(&pool, tree.path()).await.expect("live scan");
    let live_entries = get_scan_entries(&pool, live_summary.scan_id)
        .await
        .expect("read live entries");

    // Build an equivalent WizTree CSV row for every entry the live scan
    // recorded, using that entry's own stored path verbatim (so the
    // reconstructed CSV-import path matches byte-for-byte).
    let mut body = String::new();
    for e in &live_entries {
        let name = if e.kind == "dir" {
            format!("{}\\", e.path)
        } else {
            e.path.clone()
        };
        let attrs = if e.kind == "dir" { 16 } else { 32 };
        // A directory's Size/Allocated are never read by the importer
        // (module doc quirk 4); a file's Size is what matters.
        let modified = e
            .mtime
            .as_deref()
            .map(to_wiztree_modified)
            .unwrap_or_else(|| "2026/01/01 00:00:00".to_string());
        body.push_str(&format!(
            "{},{},{},{},{},0,0,0,0\r\n",
            quote(&name),
            e.size,
            e.size,
            modified,
            attrs
        ));
    }
    let csv_dir = TempDir::new().expect("csv tempdir");
    let csv_path = csv_dir.path().join("equivalent.csv");
    std::fs::write(&csv_path, format!("{PREAMBLE_AND_HEADER}{body}")).expect("write csv");

    let csv_summary = run_csv_import(&pool, &csv_path).await.expect("csv import");
    assert_eq!(
        csv_summary.skipped_count, 0,
        "the constructed CSV is well-formed"
    );
    let csv_entries = get_scan_entries(&pool, csv_summary.scan_id)
        .await
        .expect("read csv entries");

    assert_eq!(
        csv_entries.len(),
        live_entries.len(),
        "the CSV import must recover the same entry count as the live scan"
    );

    // Compare by path (identical strings between the two snapshots by
    // construction): kind, size, depth, and class must agree. mtime and
    // allocated size are documented differences and are not compared (this
    // phase's brief; mtime precision, allocated size).
    use std::collections::HashMap;
    let by_path: HashMap<&str, &abo_core::ipc::EntryRow> =
        csv_entries.iter().map(|e| (e.path.as_str(), e)).collect();

    for live in &live_entries {
        let csv_e = by_path
            .get(live.path.as_str())
            .unwrap_or_else(|| panic!("csv import missing path {}", live.path));
        assert_eq!(csv_e.kind, live.kind, "kind mismatch for {}", live.path);
        assert_eq!(
            csv_e.file_class, live.file_class,
            "file_class mismatch for {}",
            live.path
        );
        assert_eq!(csv_e.size, live.size, "size mismatch for {}", live.path);
        assert_eq!(csv_e.depth, live.depth, "depth mismatch for {}", live.path);
    }
}

// ---------------------------------------------------------------------------
// Real-file import (G-07 / FD-18 baseline source). Ignored by default: the
// file lives under `_local/prior-work/`, never committed, so CI never has it.
// Run locally: cargo test -p abo-core --test csv_import -- --ignored
// ---------------------------------------------------------------------------

/// The real 2026-03-25 WizTree export path, relative to the repo root.
fn real_csv_path() -> std::path::PathBuf {
    // CARGO_MANIFEST_DIR is crates/abo-core; the repo root is two levels up.
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../_local/prior-work/WizTree_2026-03-25.csv")
}

/// AC-102.1 against the real rescued 2026-03-25 snapshot: importing it
/// produces a valid `source = csv` snapshot whose counts feed the P7 baseline
/// comparison (G-07). `#[ignore]`d because `_local/` is never committed, so a
/// CI runner never has this file; run locally with `--ignored`.
#[ignore = "reads the real, uncommitted _local/prior-work/WizTree_2026-03-25.csv; \
            run locally with `cargo test -p abo-core --test csv_import -- --ignored`"]
#[tokio::test]
async fn import_real_wiztree_2026_03_25_csv() {
    let path = real_csv_path();
    assert!(
        path.is_file(),
        "expected the real WizTree export at {}; this test only runs locally \
         where _local/prior-work/ is present",
        path.display()
    );

    let (_db, pool) = fresh_pool().await;
    let summary = run_csv_import(&pool, &path).await.expect("import real csv");

    assert_eq!(summary.status, "completed");
    assert_eq!(summary.root_path, r"E:\Books - Audio");

    let entries = get_scan_entries(&pool, summary.scan_id)
        .await
        .expect("read entries");
    let dirs = entries.iter().filter(|e| e.kind == "dir").count();
    let files = entries.iter().filter(|e| e.kind == "file").count();

    // Printed (not just asserted) so `cargo test -- --ignored --nocapture`
    // surfaces the numbers this phase's report pastes for the P7 baseline.
    println!(
        "real WizTree 2026-03-25 import: entry_count={} total_bytes={} \
         skipped_count={} dirs={} files={}",
        summary.entry_count, summary.total_bytes, summary.skipped_count, dirs, files
    );

    assert_eq!(
        summary.skipped_count, 0,
        "the real file has no malformed rows"
    );
    assert_eq!(summary.entry_count, 14689);
    assert_eq!(summary.total_bytes, 319_290_437_409);
    assert_eq!(dirs, 719);
    assert_eq!(files, 13970);
}
