//! WizTree CSV import (F-102): parses a WizTree "Export to CSV" file into the
//! same `entries` schema a live scan produces, flagged `source = csv`, so
//! classification and parsing (later phases) run identically on either source.
//!
//! ## The real-file quirks this parser is built around
//!
//! Inspecting `_local/prior-work/WizTree_2026-03-25.csv` (3.2 MB, 14689 data
//! rows) directly, rather than assuming a textbook WizTree format, surfaced
//! four load-bearing quirks:
//!
//! 1. **A 1-line human-readable preamble** (`Generated by WizTree 4.30 ...`)
//!    precedes the real header row. [`parse_wiztree_csv`] finds the header by
//!    its known leading column name (`File Name,`) rather than assuming a
//!    fixed preamble length, so it also tolerates a 0-line or 2-line preamble
//!    from other WizTree versions (this phase's brief flagged the variance).
//! 2. **Variable field count.** The header names 13 columns (through
//!    `RESERVEDSPACE`), but only the very first data row (the scanned root)
//!    ever carries all 13; every other row - all 14688 of them in the real
//!    file - carries exactly 9 (through `FOLDERALLOCATED`). The last four
//!    columns (drive capacity/free/used/reserved space) are WizTree's
//!    one-time whole-drive stats, attached to the first row rather than
//!    repeated on every one. This parser reads only the first 5 columns
//!    positionally (`File Name`, `Size`, `Allocated`, `Modified`,
//!    `Attributes`) and ignores the rest, so the variable width never matters;
//!    `csv::ReaderBuilder::flexible(true)` is required so the crate does not
//!    reject the short rows outright.
//! 3. **Directory vs. file is decided by a trailing backslash, not the
//!    `Attributes` bit.** Every folder row's `File Name` ends in `\`; file
//!    rows never do. The `Attributes` directory bit (`0x10`) agrees with this
//!    on every row of the real file except the scanned root itself (whose
//!    `Attributes` is `0`), so the trailing separator is the only fully
//!    reliable signal (see [`is_dir_name`]).
//! 4. **`Size` for a directory is its RECURSIVE total; `FOLDERSIZE` (unused
//!    here) is the sum of files directly inside it, non-recursive.** For a
//!    leaf folder holding files but no subfolders the two are equal; for an
//!    ancestor folder they diverge by orders of magnitude. Since the
//!    persisted `entries.size` is 0 for every directory (matching a live
//!    scan's `WalkedEntry`, see `crate::scan::walk`), neither directory column
//!    is read at all: only a FILE row's `Size` feeds `entries.size`, matching
//!    the live walker's `metadata.len()` semantics (confirmed against the real
//!    file: summing every file row's `Size` equals the scanned root's own
//!    `Size` value exactly).
//!
//! ## Cross-platform path handling (the load-bearing design choice)
//!
//! A WizTree path is always Windows backslash-delimited text, REGARDLESS of
//! which OS is running the import - unlike a live scan, whose paths always use
//! the host's own native separator because `walkdir` built them on that host.
//! This crate's test matrix runs on both ubuntu and windows (docs/internal/
//! ci-plan.md), and `std::path::Path` only treats `\` as a separator when
//! compiled for Windows: on Linux, a `PathBuf` built from a raw WizTree string
//! degenerates to a single opaque component, so `Path::parent()` /
//! `Path::components()` would silently misparse it (every row would appear
//! parentless) rather than fail loudly. To avoid that, every structural
//! decision here - directory detection, the parent path, the depth, the final
//! name - is done with plain string/`split('\\')` logic ([`is_dir_name`],
//! [`backslash_parent`], [`segment_count`], [`backslash_file_name`]), never
//! with `Path`'s OS-aware methods. `PathBuf` is used only as
//! [`WalkedEntry::path`]'s storage type (its `Display`/`to_string_lossy` round
//! trip the original text unchanged on every platform); `persist_entries_and_
//! finalize` takes a caller-supplied `parent_of` closure precisely so this
//! module can plug in the backslash-aware version instead of the live
//! scanner's native one (see `crate::scan::persist`).
//!
//! ## The `Modified` timestamp is relabeled, not converted
//!
//! WizTree's `Modified` column (`YYYY/MM/DD HH:MM:SS`) carries no timezone; it
//! is the exporting machine's local time. [`reformat_modified`] is a pure text
//! reformat into the walker's ISO-8601 shape (`YYYY-MM-DDTHH:MM:SSZ`) - it
//! relabels the value `Z` rather than correcting it to true UTC, since a real
//! conversion needs timezone-database access this crate deliberately does not
//! carry (migration 0001's no-chrono rationale extends here). This is a
//! documented, accepted difference from a live scan's true-UTC `mtime` (this
//! phase's brief's "mtime precision" caveat; see the parity test below).
//!
//! ## Malformed rows (AC-102.3)
//!
//! [`parse_wiztree_csv`] never aborts on a single bad row: a row whose
//! required fields are missing or fail to parse is recorded as one
//! [`AppError::CsvParse`] (carrying its 1-based data-row index) in
//! `skipped_rows` and excluded from `entries`, while every other row is still
//! imported (recover-and-continue). A WHOLLY invalid file - no `File Name,`
//! header found anywhere, or every data row malformed - fails cleanly with
//! `AppError::CsvParse { row: 0 }` before any `scans` row is written, the same
//! before-any-write posture `crate::scan::run_scan` uses for a bad root.

use std::path::{Path, PathBuf};

use sqlx::SqlitePool;

use crate::error::AppError;
use crate::ipc::ScanSummary;
use crate::scan::persist::{insert_running_scan, mark_scan_failed, persist_entries_and_finalize};
use crate::scan::typing::classify_path;
use crate::scan::walk::{now_iso8601_utc, EntryKind, WalkedEntry};

/// True when `name` (a raw WizTree `File Name` column value) denotes a
/// directory. See the module doc's quirk (3): the trailing backslash, not the
/// `Attributes` bit, is the fully reliable signal.
fn is_dir_name(name: &str) -> bool {
    name.ends_with('\\')
}

/// Strip WizTree's trailing directory backslash, if present, so the stored
/// path matches the live scanner's convention (no trailing separator).
fn strip_trailing_backslash(name: &str) -> &str {
    name.strip_suffix('\\').unwrap_or(name)
}

/// Count non-empty backslash-delimited segments, e.g. `E:\A\B` -> 3 (`E:`,
/// `A`, `B`). Deliberately plain string splitting, not `Path::components()`
/// (see the module doc's cross-platform-path section).
fn segment_count(path: &str) -> usize {
    path.split('\\').filter(|s| !s.is_empty()).count()
}

/// The final backslash-delimited segment of `path` (its "file name"). Plain
/// string splitting for the same cross-platform reason as [`segment_count`].
fn backslash_file_name(path: &str) -> &str {
    match path.rfind('\\') {
        Some(idx) => &path[idx + 1..],
        None => path,
    }
}

/// `path`'s parent, as a stored-form [`PathBuf`], or `None` when `path` has
/// only one backslash-delimited segment (a bare drive letter, which has no
/// backslash at all). Plain string splitting for the same cross-platform
/// reason as [`segment_count`]; this is the function [`run_csv_import`] hands
/// to `persist_entries_and_finalize` as its `parent_of` closure.
///
/// For the imported root itself (e.g. `E:\Lib`), this returns
/// `Some("E:")` - a path that was never actually inserted as an entry, since
/// WizTree never emits a row for the bare drive letter. `persist_entries_and_
/// finalize`'s map lookup on that key naturally misses, so the root still ends
/// up with `parent_id = NULL`; no special-casing of the root is needed here.
fn backslash_parent(path: &str) -> Option<PathBuf> {
    let idx = path.rfind('\\')?;
    Some(PathBuf::from(&path[..idx]))
}

/// Reformat a WizTree `Modified` value (`YYYY/MM/DD HH:MM:SS`) into the
/// walker's ISO-8601 UTC shape (`YYYY-MM-DDTHH:MM:SSZ`). See the module doc's
/// timestamp section: this is a text reformat, not a timezone conversion.
/// Returns `None` when `raw` does not match the expected shape or any
/// component is out of range, which makes the row a malformed-row case.
fn reformat_modified(raw: &str) -> Option<String> {
    let (date, time) = raw.split_once(' ')?;

    let mut d = date.split('/');
    let y = d.next()?;
    let mo = d.next()?;
    let da = d.next()?;
    if d.next().is_some() || y.len() != 4 {
        return None;
    }

    let mut t = time.split(':');
    let hh = t.next()?;
    let mm = t.next()?;
    let ss = t.next()?;
    if t.next().is_some() {
        return None;
    }

    let y: u32 = y.parse().ok()?;
    let mo: u32 = mo.parse().ok()?;
    let da: u32 = da.parse().ok()?;
    let hh: u32 = hh.parse().ok()?;
    let mm: u32 = mm.parse().ok()?;
    let ss: u32 = ss.parse().ok()?;
    if !(1..=12).contains(&mo) || !(1..=31).contains(&da) || hh > 23 || mm > 59 || ss > 59 {
        return None;
    }

    Some(format!("{y:04}-{mo:02}-{da:02}T{hh:02}:{mm:02}:{ss:02}Z"))
}

/// One successfully parsed data row, before depth is known (depth needs the
/// whole file's shallowest path, resolved once every row has been read).
struct RawRow {
    /// Original WizTree text with the trailing directory backslash already
    /// stripped (so it matches the stored-path convention).
    path: String,
    kind: EntryKind,
    /// 0 for directories (matching a live scan); a file's raw `Size` column
    /// otherwise (module doc quirk 4).
    size: u64,
    mtime: String,
}

/// Parse one CSV data record into a [`RawRow`], or `None` if it is malformed
/// (a required field missing, or a field present but unparsable).
fn parse_row(record: &csv::StringRecord) -> Option<RawRow> {
    let name = record.get(0)?;
    let size_raw = record.get(1)?;
    let _allocated_raw = record.get(2)?; // present in the header; unused (see module doc quirk 4)
    let modified_raw = record.get(3)?;
    let attrs_raw = record.get(4)?;

    if name.is_empty() {
        return None;
    }

    // Attributes must parse even though only the trailing-backslash signal
    // (not this bit) decides file-vs-dir (module doc quirk 3): validating it
    // is what makes a row with a garbled Attributes column a malformed row
    // rather than one silently accepted with unvalidated data.
    let _attrs: u32 = attrs_raw.parse().ok()?;

    let kind = if is_dir_name(name) {
        EntryKind::Dir
    } else {
        EntryKind::File
    };
    let size: u64 = match kind {
        EntryKind::Dir => 0,
        EntryKind::File => size_raw.parse().ok()?,
    };

    let mtime = reformat_modified(modified_raw)?;

    let path = strip_trailing_backslash(name);
    if path.is_empty() {
        return None;
    }

    Some(RawRow {
        path: path.to_string(),
        kind,
        size,
        mtime,
    })
}

/// The result of [`parse_wiztree_csv`]: entries ready for
/// `persist_entries_and_finalize`, one [`AppError::CsvParse`] per recovered
/// bad row, and the stored path of the shallowest entry (the folder WizTree
/// was pointed at), used as the imported snapshot's `scans.root_path`.
pub(crate) struct CsvParseOutcome {
    pub entries: Vec<WalkedEntry>,
    pub skipped_rows: Vec<AppError>,
    pub root_path: String,
}

/// Parse a WizTree CSV export at `csv_path` into [`CsvParseOutcome`]. See the
/// module doc for the real-file quirks this handles and the malformed-row
/// recovery contract (AC-102.3).
pub(crate) fn parse_wiztree_csv(csv_path: &Path) -> Result<CsvParseOutcome, AppError> {
    let bytes = std::fs::read(csv_path).map_err(|_| AppError::CsvParse { row: 0 })?;
    let text = String::from_utf8_lossy(&bytes);
    let text: &str = text.strip_prefix('\u{feff}').unwrap_or(&text);

    // Find the header by its known leading column name rather than assuming a
    // fixed preamble length (module doc quirk 1). No name lines can embed a
    // raw newline (Windows forbids it in file/folder names), so splitting on
    // lines first never corrupts a quoted field.
    let lines: Vec<&str> = text.lines().collect();
    let header_idx = lines
        .iter()
        .position(|line| line.starts_with("File Name,"))
        .ok_or(AppError::CsvParse { row: 0 })?;
    let body = lines[header_idx..].join("\n");

    // `flexible(true)` is load-bearing: real rows have either 9 or 13 fields
    // depending on whether the drive-capacity columns are present (module doc
    // quirk 2); without it every short row would be a hard record error.
    let mut reader = csv::ReaderBuilder::new()
        .has_headers(true)
        .flexible(true)
        .from_reader(body.as_bytes());

    let mut raw: Vec<RawRow> = Vec::new();
    let mut skipped_rows: Vec<AppError> = Vec::new();

    for (i, record) in reader.records().enumerate() {
        let row = i + 1; // 1-based data-row index; preamble/header excluded
        match record {
            Ok(r) => match parse_row(&r) {
                Some(parsed) => raw.push(parsed),
                None => skipped_rows.push(AppError::CsvParse { row }),
            },
            Err(_) => skipped_rows.push(AppError::CsvParse { row }),
        }
    }

    if raw.is_empty() {
        // Nothing usable: either there were no data rows, or every one was
        // malformed. Either way this is the "wholly invalid file" case
        // (AC-102.3's edge case), not a valid empty snapshot.
        return Err(AppError::CsvParse { row: 0 });
    }

    // The root is the shallowest parsed path (WizTree always exports a single
    // chosen folder as its first row; picking the minimum rather than trusting
    // row order is robust to any future reordering).
    let root_segments = raw
        .iter()
        .map(|r| segment_count(&r.path))
        .min()
        .expect("raw is non-empty (checked above)");
    let root_path = raw
        .iter()
        .find(|r| segment_count(&r.path) == root_segments)
        .expect("root_segments is a value taken from this same iterator")
        .path
        .clone();

    let mut entries: Vec<WalkedEntry> = raw
        .into_iter()
        .map(|r| {
            let name = backslash_file_name(&r.path).to_string();
            let file_class = match r.kind {
                // Classify from the isolated final name only (no embedded
                // separators), so extension lookup is correct on every host
                // regardless of how `Path` would parse the full CSV string
                // (module doc's cross-platform-path section).
                EntryKind::File => Some(classify_path(Path::new(&name))),
                EntryKind::Dir => None,
            };
            let depth = segment_count(&r.path).saturating_sub(root_segments);
            WalkedEntry {
                path: PathBuf::from(r.path),
                name,
                kind: r.kind,
                file_class,
                size: r.size,
                mtime: Some(r.mtime),
                depth,
            }
        })
        .collect();

    // Same determinism / parent-before-child sort the live walker performs
    // (crate::scan::walk), so persist_entries_and_finalize's single-pass
    // parent lookup sees every parent before its children.
    entries.sort_by(|a, b| a.path.cmp(&b.path));

    Ok(CsvParseOutcome {
        entries,
        skipped_rows,
        root_path,
    })
}

/// Import a WizTree CSV export (F-102) as a new immutable snapshot flagged
/// `source = csv`. Mirrors [`crate::scan::run_scan`]'s shape: parse and
/// validate before any DB write, insert a `running` `scans` row, bulk-insert
/// entries in one transaction (sharing `persist`'s insertion code with a live
/// scan via a backslash-aware `parent_of`, so a CSV-imported snapshot is
/// schema-identical downstream, AC-102.1), then finalize.
///
/// Isolated malformed rows are recovered from: `parse_wiztree_csv` skips them
/// and this function logs each one (`tracing::warn!`) and folds the count into
/// [`ScanSummary::skipped_count`] rather than aborting the import (AC-102.3).
/// `ScanSummary::warnings` is always empty for a CSV import: the structured
/// [`crate::ipc::ScanWarningKind`] enum is a frozen IPC surface with no
/// CSV-row-skip variant yet (deliberately out of this phase's scope; skipped
/// rows are still fully accounted for via `skipped_count` and the trace log).
///
/// A wholly invalid file fails cleanly with `AppError::CsvParse { row: 0 }`
/// before any `scans` row is written, the same before-any-write posture
/// `run_scan` uses for a bad root.
pub async fn run_csv_import(pool: &SqlitePool, csv_path: &Path) -> Result<ScanSummary, AppError> {
    let parsed = parse_wiztree_csv(csv_path)?;

    for skipped in &parsed.skipped_rows {
        if let AppError::CsvParse { row } = skipped {
            tracing::warn!(
                row,
                path = %csv_path.display(),
                "csv import: row skipped (malformed); continuing"
            );
        }
    }

    let started_at = now_iso8601_utc();
    tracing::info!(
        root = %parsed.root_path,
        path = %csv_path.display(),
        "csv import: started"
    );

    let scan_id = insert_running_scan(pool, "csv", &parsed.root_path, &started_at).await?;

    let (entry_count, total_bytes, completed_at) =
        match persist_entries_and_finalize(pool, scan_id, &parsed.entries, |path| {
            let s = path.to_string_lossy();
            backslash_parent(&s)
        })
        .await
        {
            Ok(v) => v,
            Err(e) => {
                mark_scan_failed(pool, scan_id).await;
                return Err(e);
            }
        };

    tracing::info!(
        scan_id,
        entry_count,
        total_bytes,
        skipped_rows = parsed.skipped_rows.len(),
        "csv import: completed"
    );

    Ok(ScanSummary {
        scan_id,
        root_path: parsed.root_path,
        entry_count,
        total_bytes,
        skipped_count: parsed.skipped_rows.len() as i64,
        started_at,
        completed_at,
        status: "completed".to_string(),
        warnings: Vec::new(),
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    // ---- Pure helper unit tests ----

    #[test]
    fn dir_detection_is_trailing_backslash() {
        assert!(is_dir_name(r"E:\Books - Audio\"));
        assert!(!is_dir_name(r"E:\Books - Audio\book.mp3"));
    }

    #[test]
    fn segment_counting_ignores_trailing_separator() {
        assert_eq!(segment_count(r"E:\A"), 2);
        assert_eq!(segment_count(r"E:\A\B"), 3);
        assert_eq!(segment_count(r"E:\A\B\C.mp3"), 4);
    }

    #[test]
    fn backslash_parent_resolves_or_is_none_with_no_separator() {
        assert_eq!(backslash_parent(r"E:\A\B"), Some(PathBuf::from(r"E:\A")));
        // The root's own "parent" is the bare drive letter, a key that was
        // never inserted as an entry - see the function's doc comment for why
        // that still yields `parent_id = NULL` for the root without special
        // casing here.
        assert_eq!(backslash_parent(r"E:\A"), Some(PathBuf::from("E:")));
        assert_eq!(backslash_parent(r"E:"), None, "no separator at all");
    }

    #[test]
    fn backslash_file_name_takes_the_last_segment() {
        assert_eq!(backslash_file_name(r"E:\A\B\book.mp3"), "book.mp3");
        assert_eq!(backslash_file_name(r"E:\A"), "A");
    }

    #[test]
    fn modified_reformats_to_iso8601_utc() {
        assert_eq!(
            reformat_modified("2026/03/25 08:50:35"),
            Some("2026-03-25T08:50:35Z".to_string())
        );
        assert_eq!(reformat_modified("not-a-date"), None);
        assert_eq!(reformat_modified("2026/13/01 00:00:00"), None, "month 13");
        assert_eq!(reformat_modified("2026/01/01 24:00:00"), None, "hour 24");
    }

    // ---- parse_wiztree_csv: structure and recovery ----

    const PREAMBLE_AND_HEADER: &str =
        "Generated by WizTree 4.30 3/25/2026 8:54:06 AM (You can hide this message by making a donation)\r\n\
         File Name,Size,Allocated,Modified,Attributes,Files,Folders,FOLDERSIZE,FOLDERALLOCATED,DRIVECAPACITY,FREESPACE,USEDSPACE,RESERVEDSPACE\r\n";

    fn write_csv(dir: &tempfile::TempDir, body: &str) -> PathBuf {
        let path = dir.path().join("sample.csv");
        std::fs::write(&path, format!("{PREAMBLE_AND_HEADER}{body}")).expect("write fixture csv");
        path
    }

    /// AC-102.1 (parser level): a small, hand-built WizTree-shaped CSV
    /// (root with the 13-field drive-stats row, a subdirectory with the usual
    /// 9 fields, and files at two depths) parses into entries with correct
    /// kinds, sizes, depths, classes, and a root with no resolvable parent.
    #[test]
    fn parses_root_subdir_and_files_with_correct_shape() {
        let dir = tempfile::TempDir::new().expect("tempdir");
        let body = "\"E:\\Lib\\\",300,304,2026/01/01 00:00:00,0,2,1,300,304,100,100,100,100\r\n\
                    \"E:\\Lib\\Sub\\\",200,204,2026/01/02 00:00:00,16,1,0,200,204\r\n\
                    \"E:\\Lib\\root.m4b\",100,104,2026/01/03 00:00:00,32,0,0,100,104\r\n\
                    \"E:\\Lib\\Sub\\nested.mp3\",200,204,2026/01/04 00:00:00,32,0,0,200,204\r\n";
        let path = write_csv(&dir, body);

        let outcome = parse_wiztree_csv(&path).expect("parse");
        assert!(outcome.skipped_rows.is_empty(), "no malformed rows here");
        assert_eq!(outcome.root_path, r"E:\Lib");
        assert_eq!(outcome.entries.len(), 4);

        let by_name = |name: &str| {
            outcome
                .entries
                .iter()
                .find(|e| e.name == name)
                .unwrap_or_else(|| panic!("missing {name}"))
        };

        let root = by_name("Lib");
        assert_eq!(root.kind, EntryKind::Dir);
        assert_eq!(root.depth, 0);
        assert_eq!(
            root.size, 0,
            "directories carry size 0, matching a live scan"
        );
        assert!(root.file_class.is_none());

        let sub = by_name("Sub");
        assert_eq!(sub.kind, EntryKind::Dir);
        assert_eq!(sub.depth, 1);

        let root_file = by_name("root.m4b");
        assert_eq!(root_file.kind, EntryKind::File);
        assert_eq!(root_file.depth, 1);
        assert_eq!(root_file.size, 100);
        assert_eq!(
            root_file.file_class,
            Some(crate::scan::typing::FileClass::Audio)
        );

        let nested = by_name("nested.mp3");
        assert_eq!(nested.depth, 2);
        assert_eq!(nested.size, 200);
    }

    /// AC-102.3: one deliberately malformed row (a non-numeric Size) is
    /// skipped and recorded with its exact 1-based row index, while the rows
    /// before and after it are still imported (recover-and-continue).
    #[test]
    fn recovers_from_one_malformed_row() {
        let dir = tempfile::TempDir::new().expect("tempdir");
        let body = "\"E:\\Lib\\\",300,304,2026/01/01 00:00:00,0,2,0,300,304,100,100,100,100\r\n\
                    \"E:\\Lib\\good1.mp3\",100,104,2026/01/02 00:00:00,32,0,0,100,104\r\n\
                    \"E:\\Lib\\bad.mp3\",NOTANUMBER,104,2026/01/03 00:00:00,32,0,0,100,104\r\n\
                    \"E:\\Lib\\good2.mp3\",150,154,2026/01/04 00:00:00,32,0,0,150,154\r\n";
        let path = write_csv(&dir, body);

        let outcome = parse_wiztree_csv(&path).expect("parse recovers");
        assert_eq!(
            outcome.skipped_rows,
            vec![AppError::CsvParse { row: 3 }],
            "row 3 (bad.mp3's Size) is the only malformed row"
        );
        assert_eq!(outcome.entries.len(), 3, "the other 3 rows still imported");
        assert!(outcome.entries.iter().any(|e| e.name == "good1.mp3"));
        assert!(outcome.entries.iter().any(|e| e.name == "good2.mp3"));
        assert!(
            !outcome.entries.iter().any(|e| e.name == "bad.mp3"),
            "the malformed row is excluded, not partially imported"
        );
    }

    /// AC-102.3's other edge: a file with no WizTree header anywhere fails
    /// cleanly with `CsvParse { row: 0 }` rather than importing nothing
    /// silently.
    #[test]
    fn wholly_invalid_file_fails_cleanly() {
        let dir = tempfile::TempDir::new().expect("tempdir");
        let path = dir.path().join("not-wiztree.csv");
        std::fs::write(&path, "this,is,not,a,wiztree,export\r\n1,2,3,4,5,6\r\n")
            .expect("write junk file");

        let result = parse_wiztree_csv(&path);
        assert!(
            matches!(result, Err(AppError::CsvParse { row: 0 })),
            "expected CsvParse{{row: 0}}, got {:?}",
            result.map(|o| o.entries.len())
        );
    }

    /// A file that has the header but every data row is malformed is the same
    /// "wholly invalid" case: nothing usable was ever produced.
    #[test]
    fn header_only_with_all_bad_rows_fails_cleanly() {
        let dir = tempfile::TempDir::new().expect("tempdir");
        let body = "\"E:\\Lib\\bad.mp3\",NOTANUMBER,104,2026/01/03 00:00:00,32,0,0,100,104\r\n";
        let path = write_csv(&dir, body);

        let result = parse_wiztree_csv(&path);
        assert!(
            matches!(result, Err(AppError::CsvParse { row: 0 })),
            "expected CsvParse{{row: 0}}, got {:?}",
            result.map(|o| o.entries.len())
        );
    }

    #[test]
    fn missing_file_fails_cleanly() {
        let dir = tempfile::TempDir::new().expect("tempdir");
        let missing = dir.path().join("does-not-exist.csv");
        let result = parse_wiztree_csv(&missing);
        assert!(matches!(result, Err(AppError::CsvParse { row: 0 })));
    }
}
